create table CodeType
(
	Id int not null,
	Name varchar(100) not null,
	constraint PK_CodeType_Id primary key (Id),
	constraint UQ_CodeType_Name unique (Name)
);

create table Code
(
	CodeTypeId int not null,
	Code varchar(10) not null,
	Value varchar(1000) not null
	constraint PK_Code_CodeTypeId_Code primary key (CodeTypeId, Code),
	constraint FK_Code_CodeTypeId foreign key (CodeTypeId) references CodeType (Id)
);

insert into CodeType
(
	Id,
	Name
)
values
(1, 'activity_location_type_code'),
(2, 'activity_treatment_function_code'),
(3, 'activity_treatment_function_code_decision_to_admit'),
(4, 'administrative_category_code'),
(5, 'administrative_category_code_on_admission'),
(6, 'admission_method_code_hospital_provider_spell'),
(7, 'admission_offer_outcome_code'),
(8, 'anaesthetic_given_during_labour_or_delivery_code'),
(9, 'anaesthetic_given_post_labour_or_delivery_code'),
(10, 'attended_or_did_not_attend_code'),
(11, 'care_professional_discharge_responsibility_indicator_emergency_care'),
(12, 'care_professional_main_specialty_code'),
(13, 'care_professional_tier_emergency_care'),
(14, 'carer_support_indicator'),
(15, 'cds_bulk_replacement_group_code'),
(16, 'cds_interchange_application_reference'),
(17, 'cds_interchange_test_indicator'),
(18, 'cds_message_type'),
(19, 'cds_message_version_number'),
(20, 'cds_protocol_identifier_code'),
(21, 'cds_type_code'),
(22, 'cds_update_type'),
(23, 'consultation_medium_used'),
(24, 'critical_care_activity_code'),
(25, 'critical_care_admission_source'),
(26, 'critical_care_admission_type'),
(27, 'critical_care_discharge_destination'),
(28, 'critical_care_discharge_location'),
(29, 'critical_care_discharge_status'),
(30, 'critical_care_source_location'),
(31, 'critical_care_unit_bed_configuration'),
(32, 'critical_care_unit_function'),
(33, 'delivery_method_code'),
(34, 'delivery_place_change_reason_code'),
(35, 'delivery_place_type_code_actual'),
(36, 'delivery_place_type_code_intended'),
(37, 'diagnosis_scheme_in_use'),
(38, 'direct_access_referral_indicator'),
(39, 'discharge_destination_code_hospital_provider_spell'),
(40, 'discharge_method_code_hospital_provider_spell'),
(41, 'discharged_to_hospital_at_home_service_indicator'),
(42, 'elective_admission_list_removal_reason_code'),
(43, 'elective_admission_list_status'),
(44, 'elective_admission_type_code'),
(45, 'emergency_care_attendance_category'),
(46, 'emergency_care_department_type'),
(47, 'ethnic_category'),
(48, 'first_attendance_code'),
(49, 'first_regular_day_or_night_admission_code'),
(50, 'intended_age_group'),
(51, 'intended_clinical_care_intensity_code'),
(52, 'intended_management_code'),
(53, 'intended_procedure_status_code'),
(54, 'labour_or_delivery_onset_method_code'),
(55, 'last_episode_in_spell_indicator_code'),
(56, 'live_or_still_birth_code'),
(57, 'location_class'),
(58, 'medical_staff_type_seeing_patient'),
(59, 'mental_health_act_2007_mental_category'),
(60, 'mental_health_act_legal_status_classification_code'),
(61, 'mental_health_act_legal_status_classification_code_at_census_date'),
(62, 'mental_health_act_legal_status_classification_code_on_admission'),
(63, 'multi_professional_or_multi_disciplinary_indication_code_payment_by_results'),
(64, 'neonatal_level_of_care_code'),
(65, 'nhs_number_status_indicator_code'),
(66, 'nhs_number_status_indicator_code_baby'),
(67, 'nhs_number_status_indicator_code_mother'),
(68, 'number_of_babies_indication_code'),
(69, 'operation_status_code'),
(70, 'outcome_of_attendance_code'),
(71, 'overseas_visitor_charging_category_at_cds_activity_date'),
(72, 'overseas_visitor_status_classification'),
(73, 'overseas_visitor_status_classification_at_cds_activity_date'),
(74, 'patient_classification_code'),
(75, 'person_gender_code_current'),
(76, 'person_gender_code_current_baby'),
(77, 'person_marital_status'),
(78, 'person_stated_gender_code'),
(79, 'present_on_admission_indicator'),
(80, 'priority_type_code'),
(81, 'procedure_scheme_in_use'),
(82, 'professional_registration_issuer_code'),
(83, 'psychiatric_patient_status_code'),
(84, 'referral_to_treatment_period_status'),
(85, 'rehabilitation_assessment_team_type'),
(86, 'resuscitation_method_code'),
(87, 'service_type_requested_code'),
(88, 'sex_of_patients_code'),
(89, 'source_of_admission_code_hospital_provider_spell'),
(90, 'source_of_referral_for_out_patients'),
(91, 'status_of_patient_included_in_the_psychiatric_census_code'),
(92, 'status_of_person_conducting_delivery_code'),
(93, 'waiting_time_measurement_type'),
(94, 'ward_day_period_availability_code'),
(95, 'ward_night_period_availability_code'),
(96, 'ward_security_level'),
(97, 'withheld_identity_reason');
	


