using OmopTransformer.Annotations;

namespace OmopTransformer.Transformation;

[Description("OXford Lab Test Lookup lookup")]
internal class LabTestLookup : ILookup
{
    public Dictionary<string, ValueWithNote> Mappings { get; } =
        new()
        {
            { "25 vitamin D comment", new ValueWithNote("0", "0") },
            { "Adjusted calcium level, blood", new ValueWithNote("40757497", "Calcium.ionized [Moles/volume] adjusted to pH 7.4 in Cord blood") },
            { "Alanine aminotransferase level, blood", new ValueWithNote("46235106", "Alanine aminotransferase [Enzymatic activity/volume] in Blood") },
            { "Albumin level, blood", new ValueWithNote("3034736", "Transfuse albumin [Volume]") },
            { "Alk phos level, blood", new ValueWithNote("0", "0") },
            { "APTT, blood", new ValueWithNote("3000944", "Deprecated Activated partial thrombplastin time (aPTT) in Blood from control by Coagulation assay") },
            { "Basophil count, blood", new ValueWithNote("3006315", "Basophils [#/volume] in Blood") },
            { "BE Act (BG)", new ValueWithNote("0", "0") },
            { "BE Std (BG)", new ValueWithNote("1091172", "Deprecated Base excess standard in Arterial blood") },
            { "Bicarb (BG)", new ValueWithNote("3008152", "Bicarbonate [Moles/volume] in Arterial blood") },
            { "Blood gases comment", new ValueWithNote("0", "0") },
            { "Blood Glucose POC", new ValueWithNote("0", "0") },
            { "Blood Ketones, POC", new ValueWithNote("0", "0") },
            { "C-reactive protein level, blood", new ValueWithNote("3051387", "C reactive protein [Mass/volume] in Capillary blood") },
            { "Ca+ + (BG)", new ValueWithNote("40762532", "Calcium.ionized [Mass/volume] in Arterial blood") },
            { "Calcium level, blood", new ValueWithNote("0", "0") },
            { "Calculated LDL cholesterol level, blood", new ValueWithNote("0", "0") },
            { "Cholesterol:HDL ratio, blood", new ValueWithNote("0", "0") },
            { "Cl- (BG)", new ValueWithNote("3031248", "Chloride [Moles/volume] in Arterial blood") },
            { "cLAC (BG)", new ValueWithNote("3035561", "Lactate [Mass/volume] in Arterial blood") },
            { "Creat (BG)", new ValueWithNote("3007760", "Creatinine [Mass/volume] in Arterial blood") },
            { "Creatinine level, blood", new ValueWithNote("40762887", "Creatinine [Moles/volume] in Blood") },
            { "Creatinine level, urine", new ValueWithNote("0", "0") },
            { "ctO2c (BG)", new ValueWithNote("40762365", "Oxygen content in Arterial blood by calculation") },
            { "eGFR comment", new ValueWithNote("0", "0") },
            { "Eosinophil count, blood", new ValueWithNote("3032917", "Immature eosinophils [#/volume] in Blood") },
            { "Estimated GFR, blood", new ValueWithNote("0", "0") },
            { "Estimated Osmolality (BG)", new ValueWithNote("0", "0") },
            { "FCOHb (BG)", new ValueWithNote("3028653", "Carboxyhemoglobin/Hemoglobin.total in Arterial blood") },
            { "Ferritin level, serum", new ValueWithNote("0", "0") },
            { "FHHb (BG))", new ValueWithNote("42869609", "Deoxyhemoglobin/Hemoglobin.total [Pure mass fraction] in Arterial blood") },
            { "FIO2", new ValueWithNote("3025408", "Oxygen/Inspired gas Respiratory system by O2 Analyzer --on ventilator") },
            { "Folate level, serum", new ValueWithNote("0", "0") },
            { "General biochemistry comment", new ValueWithNote("0", "0") },
            { "Glucose (BG)", new ValueWithNote("0", "0") },
            { "Glucose level, plasma", new ValueWithNote("0", "0") },
            { "Glycated haemoglobin reference, blood", new ValueWithNote("0", "0") },
            { "Haematocrit level, blood", new ValueWithNote("3964676", "Basic metabolic and hematocrit panel - Blood") },
            { "Haematology comment", new ValueWithNote("40761546", "Manual differential comment [Interpretation] in Blood Narrative") },
            { "Haemoglobin", new ValueWithNote("0", "0") },
            { "Haemoglobin A1c DCCT aligned, blood", new ValueWithNote("40758583", "Deprecated Hemoglobin A1c in Blood") },
            { "Hb (BG)", new ValueWithNote("0", "0") },
            { "HBA1c comment", new ValueWithNote("0", "0") },
            { "Hct (BG)", new ValueWithNote("3023230", "Hematocrit [Volume Fraction] of Arterial blood by calculation") },
            { "HDL cholesterol level, blood", new ValueWithNote("36031550", "Cholesterol.total/Cholesterol in HDL [Mass Ratio] in DBS") },
            { "Immature Granulocytes count, blood", new ValueWithNote("3040168", "Immature granulocytes [#/volume] in Blood") },
            { "Inorganic phosphate level, blood", new ValueWithNote("3024232", "Phosphate [Mass/volume] in Blood") },
            { "Iron level, serum", new ValueWithNote("3031616", "Iron and Iron binding capacity panel - Serum or Plasma") },
            { "K+ (BG)", new ValueWithNote("3043409", "Potassium [Moles/volume] in Arterial blood") },
            { "Lymphocyte count, blood", new ValueWithNote("3030137", "Lymphocyte proliferation stimulated by concanavalin A in Blood") },
            { "Magnesium level, blood", new ValueWithNote("0", "0") },
            { "Mean cell haemoglobin conc, blood", new ValueWithNote("46235811", "Reticulocyte corpuscular hemoglobin concentration mean [Mass/volume] in Blood") },
            { "Mean cell haemoglobin level, blood", new ValueWithNote("46235811", "Reticulocyte corpuscular hemoglobin concentration mean [Mass/volume] in Blood") },
            { "Mean cell volume, blood", new ValueWithNote("3039385", "Mean sphered cell volume [Entitic volume] in Red Blood Cells") },
            { "Mean platelet volume, blood", new ValueWithNote("3042838", "Deprecated Platelet mean volume [Entitic volume] in Blood by Automated count") },
            { "MetHb (BG)", new ValueWithNote("3006217", "Methemoglobin/Hemoglobin.total in Arterial blood") },
            { "Miscellaneous Immunology comment", new ValueWithNote("0", "0") },
            { "Monocyte count, blood", new ValueWithNote("1091096", "Monocyte and dendritic cell panel - Blood by Flow cytometry (FC)") },
            { "Na+ (BG)", new ValueWithNote("3043706", "Sodium [Moles/volume] in Arterial blood") },
            { "Neutrophil count, blood", new ValueWithNote("3022198", "Neutrophil oxidative burst [Presence] in Blood by Flow cytometry (FC)") },
            { "Non-HDL cholesterol, blood", new ValueWithNote("0", "0") },
            { "NRBC count per 100 WBC, blood", new ValueWithNote("0", "0") },
            { "Nucleated red blood cell count, blood", new ValueWithNote("3001490", "Nucleated erythrocytes [#/volume] in Blood") },
            { "O2 Sat (BG)", new ValueWithNote("3016502", "Oxygen saturation in Arterial blood") },
            { "O_Bone profile, blood", new ValueWithNote("0", "0") },
            { "O_C-reactive protein level, blood", new ValueWithNote("3051387", "C reactive protein [Mass/volume] in Capillary blood") },
            { "O_Clotting screen, blood", new ValueWithNote("3031674", "Blood coagulation device panel") },
            { "O_Full Blood Count", new ValueWithNote("1001626", "PhenX - complete blood count protocol 220501") },
            { "O_Liver function screen, blood", new ValueWithNote("0", "0") },
            { "O_Magnesium level, blood", new ValueWithNote("0", "0") },
            { "O_Urea and electrolytes, blood", new ValueWithNote("0", "0") },
            { "p5Oc (BG)", new ValueWithNote("0", "0") },
            { "pCO2 POC", new ValueWithNote("0", "0") },
            { "pCO2(T)c", new ValueWithNote("0", "0") },
            { "pH (BG)", new ValueWithNote("3019977", "pH of Arterial blood") },
            { "pH(T)c", new ValueWithNote("0", "0") },
            { "Platelet count, blood", new ValueWithNote("3051319", "Platelets [#/volume] in Cord blood") },
            { "pO2 (BG)", new ValueWithNote("3027801", "Oxygen [Partial pressure] in Arterial blood") },
            { "pO2(T)c", new ValueWithNote("0", "0") },
            { "Potassium level, blood", new ValueWithNote("21490733", "Potassium [Mass/volume] in Blood") },
            { "Prothrombin time and INR, blood", new ValueWithNote("3032080", "INR in Blood by Coagulation assay") },
            { "Prothrombin time, blood", new ValueWithNote("3002417", "Prothrombin time (PT) in Blood by Coagulation assay") },
            { "Red blood cell count, blood", new ValueWithNote("3052191", "Erythrocytes [#/volume] in Cord blood") },
            { "Red Blood Cell Distribution Width", new ValueWithNote("3002888", "Deprecated Erythrocyte distribution width [Entitic volume]") },
            { "Sodium level, blood", new ValueWithNote("3043706", "Sodium [Moles/volume] in Arterial blood") },
            { "Specimen type (BG)", new ValueWithNote("0", "0") },
            { "Temperature POCT", new ValueWithNote("0", "0") },
            { "Thyroid stimulating hormone, blood", new ValueWithNote("40766096", "Thyrotropin receptor Ab [Units/volume] in Cord blood") },
            { "Total bilirubin level, blood", new ValueWithNote("3028833", "Bilirubin.total [Mass/volume] in Blood") },
            { "Total cholesterol level, blood", new ValueWithNote("36031550", "Cholesterol.total/Cholesterol in HDL [Mass Ratio] in DBS") },
            { "Transferrin level, blood", new ValueWithNote("36203863", "Transferrin.gastrointestinal [Mass/volume] in Stool by Immunoassay") },
            { "Transferrin Saturation", new ValueWithNote("0", "0") },
            { "Triglycerides level, blood", new ValueWithNote("3022038", "Triglyceride [Mass/volume] in Blood") },
            { "Urea level, plasma", new ValueWithNote("0", "0") },
            { "Vitamin B12 level, serum", new ValueWithNote("3031790", "Cobalamin (Vitamin B12) [Mass or Moles/volume] in Serum") },
            { "Vitamin D level, blood", new ValueWithNote("40758935", "25-hydroxyvitamin D3 [Moles/volume] in Cord blood") },
            { "Warfarin comment", new ValueWithNote("0", "0") },
            { "Warfarin Dose", new ValueWithNote("3024105", "Warfarin [Mass] of Dose") },
            { "White blood cell count, blood", new ValueWithNote("3045406", "Plasma cell precursor/Leukocytes in Blood by Manual count") },
        };

    public string[] ColumnNotes =>
    [
    ];
}