using OmopTransformer.Annotations;

namespace OmopTransformer.Transformation;

[Description("OXford Lab Test Lookup lookup")]
internal class LabTestLookup : ILookup
{
    public Dictionary<string, ValueWithNote> Mappings { get; } =
        new()
        {
            { "Adjusted calcium level, blood", new ValueWithNote("3048816", "Calcium.ionized [Moles/volume] adjusted to pH 7.4 in Blood") },
            { "Alanine aminotransferase level, blood", new ValueWithNote("46235106", "Alanine aminotransferase [Enzymatic activity/volume] in Blood") },
            { "Albumin level, blood", new ValueWithNote("3043798", "Albumin [Presence] in Serum or Plasma") },
            { "Alk phos level, blood", new ValueWithNote("3003650", "Alkaline phosphatase [Mass/volume] in Body fluid") },
            { "APTT, blood", new ValueWithNote("3013466", "aPTT in Blood by Coagulation assay") },
            { "Basophil count, blood", new ValueWithNote("3006315", "Basophils [#/volume] in Blood") },
            { "BE Act (BG)", new ValueWithNote("3005724", "B Ag [Presence] on Red Blood Cells") },
            { "BE Std (BG)", new ValueWithNote("3025597", "Deprecated Chlamydia trachomatis G+F+K Ab [Units/volume] in Serum") },
            { "Bicarb (BG)", new ValueWithNote("3005724", "B Ag [Presence] on Red Blood Cells") },
            { "Blood gases comment", new ValueWithNote("44786790", "Volatiles and gases [Presence] in Blood") },
            { "Blood Glucose POC", new ValueWithNote("3020491", "Glucose [Moles/volume] in Blood") },
            { "Blood Ketones, POC", new ValueWithNote("3041426", "Ketones [Moles/volume] in Blood") },
            { "C-reactive protein level, blood", new ValueWithNote("1091617", "C reactive protein [Mass/volume] in Serum, Plasma or Blood") },
            { "Ca+ + (BG)", new ValueWithNote("3036426", "Calcium.ionized [Mass/volume] in Blood") },
            { "Calcium level, blood", new ValueWithNote("3027495", "Calcium [Presence] in Blood") },
            { "Calculated LDL cholesterol level, blood", new ValueWithNote("3028288", "Cholesterol in LDL [Mass/volume] in Serum or Plasma by calculation") },
            { "Cholesterol:HDL ratio, blood", new ValueWithNote("3024723", "Cholesterol/Triglyceride [Mass Ratio] in Serum or Plasma") },
            { "Cl- (BG)", new ValueWithNote("46235783", "Chloride [Moles/volume] in Serum, Plasma or Blood") },
            { "cLAC (BG)", new ValueWithNote("3034564", "CLA2 gene mutations found [Identifier] in Blood or Tissue by Molecular genetics method Nominal") },
            { "Creat (BG)", new ValueWithNote("3026159", "Suberate [Presence] in Urine") },
            { "Creatinine level, blood", new ValueWithNote("3051825", "Creatinine [Mass/volume] in Blood") },
            { "Creatinine level, urine", new ValueWithNote("3007081", "Creatinine [Interpretation] in Urine") },
            { "ctO2c (BG)", new ValueWithNote("40763341", "Ascorbate [Moles/volume] in Specimen") },
            { "eGFR comment", new ValueWithNote("40758890", "EGFR gene c.2369C>T [Presence] in Blood or Tissue by Molecular genetics method") },
            { "Eosinophil count, blood", new ValueWithNote("3013115", "Eosinophils [#/volume] in Blood") },
            { "Estimated GFR, blood", new ValueWithNote("3045262", "Creatinine and Glomerular filtration rate.predicted panel - Serum, Plasma or Blood") },
            { "Estimated Osmolality (BG)", new ValueWithNote("3008295", "Osmolality of Serum or Plasma") },
            { "FCOHb (BG)", new ValueWithNote("3033821", "Fy sup(b) Ab [Presence] in Serum or Plasma from Blood product unit") },
            { "Ferritin level, serum", new ValueWithNote("3001122", "Ferritin [Mass/volume] in Serum or Plasma") },
            { "FIO2", new ValueWithNote("3006455", "Oxygen [Partial pressure] in Exhaled gas") },
            { "Folate level, serum", new ValueWithNote("3033201", "Folate [Mass/volume] in Serum or Plasma") },
            { "General biochemistry comment", new ValueWithNote("3025981", "Arginine+Argininosuccinate+Lysine+Serine+Taurine [Presence] in Urine") },
            { "Glucose (BG)", new ValueWithNote("3000483", "Glucose [Mass/volume] in Blood") },
            { "Glucose level, plasma", new ValueWithNote("44816672", "Glucose [Mass/volume] in Serum, Plasma or Blood") },
            { "Glycated haemoglobin reference, blood", new ValueWithNote("3005131", "Glucose mean value [Mass/volume] in Blood Estimated from glycated hemoglobin") },
            { "Haematocrit level, blood", new ValueWithNote("3009542", "Hematocrit [Volume Fraction] of Blood by calculation") },
            { "Haematology comment", new ValueWithNote("40762529", "Hematologist review of results") },
            { "Haemoglobin", new ValueWithNote("3000963", "Hemoglobin [Mass/volume] in Blood") },
            { "Haemoglobin A1c DCCT aligned, blood", new ValueWithNote("3005673", "Hemoglobin A1c/Hemoglobin.total in Blood by HPLC") },
            { "Hb (BG)", new ValueWithNote("3041888", "Hemoglobin H [Presence] in Blood") },
            { "HBA1c comment", new ValueWithNote("3005673", "Hemoglobin A1c/Hemoglobin.total in Blood by HPLC") },
            { "Hct (BG)", new ValueWithNote("36203329", "Bg sup(b) Ag [Presence] on Red Blood Cells") },
            { "HDL cholesterol level, blood", new ValueWithNote("3011884", "Cholesterol in HDL [Presence] in Serum or Plasma") },
            { "Immature Granulocytes count, blood", new ValueWithNote("3040168", "Immature granulocytes [#/volume] in Blood") },
            { "Inorganic phosphate level, blood", new ValueWithNote("3024232", "Phosphate [Mass/volume] in Blood") },
            { "Iron level, serum", new ValueWithNote("3021862", "Iron [Interpretation] in Serum or Plasma") },
            { "K+ (BG)", new ValueWithNote("21490733", "Potassium [Mass/volume] in Blood") },
            { "Lymphocyte count, blood", new ValueWithNote("3019198", "Lymphocytes [#/volume] in Blood") },
            { "Magnesium level, blood", new ValueWithNote("3006916", "Magnesium [Presence] in Blood") },
            { "Mean cell haemoglobin conc, blood", new ValueWithNote("3000963", "Hemoglobin [Mass/volume] in Blood") },
            { "Mean cell haemoglobin level, blood", new ValueWithNote("3000963", "Hemoglobin [Mass/volume] in Blood") },
            { "Mean cell volume, blood", new ValueWithNote("3033607", "Volume of Blood") },
            { "Mean platelet volume, blood", new ValueWithNote("3001123", "Platelet [Entitic mean volume] in Blood") },
            { "MetHb (BG)", new ValueWithNote("3008524", "Presence in Serum or Plasma") },
            { "Miscellaneous Immunology comment", new ValueWithNote("3029658", "Other cells/Leukocytes in Body fluid") },
            { "Monocyte count, blood", new ValueWithNote("3001604", "Monocytes [#/volume] in Blood") },
            { "Na+ (BG)", new ValueWithNote("3000285", "Sodium [Moles/volume] in Blood") },
            { "Neutrophil count, blood", new ValueWithNote("3017732", "Neutrophils [#/volume] in Blood") },
            { "Non-HDL cholesterol, blood", new ValueWithNote("3044491", "Cholesterol non HDL [Mass/volume] in Serum or Plasma") },
            { "NRBC count per 100 WBC, blood", new ValueWithNote("3020036", "Deprecated Nucleated Erythrocytes/100 leukocytes [Ratio] in Blood") },
            { "Nucleated red blood cell count, blood", new ValueWithNote("3001490", "Nucleated erythrocytes [#/volume] in Blood") },
            { "O2 Sat (BG)", new ValueWithNote("3016502", "Oxygen saturation in Arterial blood") },
            { "O_Bone profile, blood", new ValueWithNote("3016185", "O group [Presence] on Red Blood Cells from Donor") },
            { "O_C-reactive protein level, blood", new ValueWithNote("3051387", "C reactive protein [Mass/volume] in Capillary blood") },
            { "O_Calcium level, blood", new ValueWithNote("3027495", "Calcium [Presence] in Blood") },
            { "O_Clotting screen, blood", new ValueWithNote("40770392", "Thromboelastography panel - Blood") },
            { "O_Full Blood Count", new ValueWithNote("3033204", "Hemoglobin O - Arab/Hemoglobin.total in Blood") },
            { "O_Magnesium level, blood", new ValueWithNote("3033836", "Magnesium [Moles/volume] in Blood") },
            { "O_Urea and electrolytes, blood", new ValueWithNote("3004295", "Urea nitrogen [Mass/volume] in Blood") },
            { "p5Oc (BG)", new ValueWithNote("3008617", "O group [Presence] on Red Blood Cells from Blood product unit") },
            { "pCO2 POC", new ValueWithNote("3013290", "Carbon dioxide [Partial pressure] in Blood") },
            { "pCO2(T)c", new ValueWithNote("3010140", "Carbon dioxide, total [Moles/volume] in Venous blood") },
            { "pH (BG)", new ValueWithNote("3010421", "pH of Blood") },
            { "pH(T)c", new ValueWithNote("1616438", "pH of Central venous blood") },
            { "Platelet count, blood", new ValueWithNote("3007461", "Platelets [#/volume] in Blood") },
            { "pO2 (BG)", new ValueWithNote("3003246", "Oxygen [Partial pressure] in Exhaled gas") },
            { "pO2(T)c", new ValueWithNote("1616654", "Oxygen [Partial pressure] in Central venous blood") },
            { "Potassium level, blood", new ValueWithNote("21490733", "Potassium [Mass/volume] in Blood") },
            { "Prothrombin time and INR, blood", new ValueWithNote("3014391", "Thrombin time [Interpretation] in Blood") },
            { "Prothrombin time, blood", new ValueWithNote("3034426", "Prothrombin time (PT)") },
            { "Red blood cell count, blood", new ValueWithNote("3026361", "Erythrocytes [#/volume] in Blood") },
            { "Red Blood Cell Distribution Width", new ValueWithNote("3002385", "Erythrocyte [DistWidth] in Red Blood Cells") },
            { "Sodium level, blood", new ValueWithNote("3000285", "Sodium [Moles/volume] in Blood") },
            { "Specimen type (BG)", new ValueWithNote("40769406", "Specimen type") },
            { "Temperature POCT", new ValueWithNote("21492846", "Environment temperature during transport") },
            { "Thyroid stimulating hormone, blood", new ValueWithNote("3011450", "Thyrotropin [Presence] in Blood") },
            { "Total bilirubin level, blood", new ValueWithNote("3028833", "Bilirubin.total [Mass/volume] in Blood") },
            { "Total cholesterol level, blood", new ValueWithNote("3012041", "Choleglobin/Hemoglobin.total in Blood") },
            { "Transferrin level, blood", new ValueWithNote("3004789", "Transferrin [Mass/volume] in Serum or Plasma") },
            { "Transferrin Saturation", new ValueWithNote("3007987", "Deprecated Transferrin saturation in Serum or Plasma") },
            { "Triglycerides level, blood", new ValueWithNote("3022038", "Triglyceride [Mass/volume] in Blood") },
            { "Urea level, plasma", new ValueWithNote("3034204", "Urea [Mass/volume] in Serum or Plasma") },
            { "Vitamin B12 level, serum", new ValueWithNote("3031790", "Cobalamin (Vitamin B12) [Mass/volume] in Serum") },
            { "Vitamin D level, blood", new ValueWithNote("36031904", "25-hydroxyvitamin D3+25-hydroxyvitamin D2 [Mass/volume] in Capillary blood") },
            { "Warfarin comment", new ValueWithNote("3026207", "Warfarin [Mass/volume] in Urine") },
            { "Warfarin Dose", new ValueWithNote("3024105", "Warfarin [Mass] of Dose") },
            { "White blood cell count, blood", new ValueWithNote("3010813", "Leukocytes [#/volume] in Blood") },
        };

    public string[] ColumnNotes =>
    [
    ];
}