using OmopTransformer.Annotations;

namespace OmopTransformer.Transformation;

[Description("SACT Drug lookup")]
internal class SactDrugLookup : ILookup
{
    public Dictionary<string, ValueWithNote> Mappings { get; } =
        new()
        {
            { "abemaciclib", new ValueWithNote("792649", "abemaciclib") },
            { "abiraterone acetate", new ValueWithNote("46274231", "abiraterone acetate") },
            { "abiraterone", new ValueWithNote("40239056", "abiraterone") },
            { "acalabrutinib", new ValueWithNote("792764", "acalabrutinib") },
            { "aciclovir", new ValueWithNote("42907410", "vaciclovir") },
            { "acp-196", new ValueWithNote("792764", "acalabrutinib") },
            { "ag-946", new ValueWithNote("1254285", "tebapivat") },
            { "alectinib", new ValueWithNote("35604657", "alectinib") },
            { "alemtuzumab", new ValueWithNote("1312706", "alemtuzumab") },
            { "allopurinol", new ValueWithNote("1167322", "allopurinol") },
            { "alpelisib", new ValueWithNote("1396423", "alpelisib") },
            { "antithymocyte immunoglobulin (rabbi", new ValueWithNote("19136207", "lymphocyte immune globulin, anti-thymocyte globulin") },
            { "apalutamide", new ValueWithNote("963987", "apalutamide") },
            { "aprepitant", new ValueWithNote("936748", "aprepitant") },
            { "arsenic trioxide", new ValueWithNote("1333379", "arsenic trioxide") },
            { "asciminib", new ValueWithNote("702133", "asciminib") },
            { "astx727 (cedazuridine 100 mg  decit", new ValueWithNote("1146672", "cedazuridine / decitabine oral tablet") },
            { "atezolizumab", new ValueWithNote("42629079", "atezolizumab") },
            { "atropine sulphate", new ValueWithNote("19018119", "atropine sulfate") },
            { "avapritinib", new ValueWithNote("37498468", "avapritinib") },
            { "avelumab", new ValueWithNote("1593273", "avelumab") },
            { "axicabtagene ciloleucel", new ValueWithNote("792844", "axicabtagene ciloleucel") },
            { "axitinib", new ValueWithNote("42709322", "axitinib") },
            { "azacitidine", new ValueWithNote("1314865", "azacitidine") },
            { "azd4573", new ValueWithNote("36856884", "azd-4573") },
            { "azd7789", new ValueWithNote("1253377", "sabestomig") },
            { "belantamab mafodotin", new ValueWithNote("37002419", "belantamab mafodotin") },
            { "bendamustine", new ValueWithNote("19015523", "bendamustine") },
            { "bevacizumab", new ValueWithNote("1397141", "bevacizumab") },
            { "bexarotene", new ValueWithNote("1389888", "bexarotene") },
            { "bi 836845", new ValueWithNote("36863086", "xentuzumab") },
            { "bi-1607", new ValueWithNote("36855886", "bd-1067") },
            { "binimetinib", new ValueWithNote("1559930", "binimetinib") },
            { "bleomycin sulphate", new ValueWithNote("19018330", "bleomycin sulfate") },
            { "blinatumomab 100mcg infusion bag (2", new ValueWithNote("45892531", "blinatumomab") },
            { "blinatumomab 133.75mcg infusion bag", new ValueWithNote("45892531", "blinatumomab") },
            { "blinatumomab 31.25mcg infusion bag ", new ValueWithNote("45892531", "blinatumomab") },
            { "blinatumomab 41.25mcg infusion bag ", new ValueWithNote("45892531", "blinatumomab") },
            { "blinatumomab", new ValueWithNote("45892531", "blinatumomab") },
            { "bortezomib", new ValueWithNote("1336825", "bortezomib") },
            { "bosutinib", new ValueWithNote("42900401", "bosutinib") },
            { "brentuximab vedotin", new ValueWithNote("40241969", "brentuximab vedotin") },
            { "brigatinib", new ValueWithNote("1594187", "brigatinib") },
            { "busulfan", new ValueWithNote("1333357", "busulfan") },
            { "cabazitaxel", new ValueWithNote("40222431", "cabazitaxel") },
            { "cabozantinib", new ValueWithNote("43012292", "cabozantinib") },
            { "calcium folinate", new ValueWithNote("36878754", "disodium folinate") },
            { "calcium levofolinate", new ValueWithNote("36256127", "calcium levofolinate") },
            { "capecitabine", new ValueWithNote("1337620", "capecitabine") },
            { "carboplatin", new ValueWithNote("1344905", "carboplatin") },
            { "carfilzomib", new ValueWithNote("42873638", "carfilzomib") },
            { "carmustine", new ValueWithNote("1350066", "carmustine") },
            { "cc-95251", new ValueWithNote("1253409", "anzurstobart") },
            { "cediranib", new ValueWithNote("36859905", "cediranib") },
            { "cemiplimab", new ValueWithNote("35200783", "cemiplimab") },
            { "ceralasertib", new ValueWithNote("36854241", "ceralasertib") },
            { "cetirizine", new ValueWithNote("1149196", "cetirizine") },
            { "cetuximab", new ValueWithNote("1315411", "cetuximab") },
            { "chlorambucil", new ValueWithNote("1390051", "chlorambucil") },
            { "chlorphenamine", new ValueWithNote("19049707", "chlorphenoxamine") },
            { "cisplatin", new ValueWithNote("1397599", "cisplatin") },
            { "cladribine", new ValueWithNote("19054825", "cladribine") },
            { "co-trimoxazole", new ValueWithNote("21018085", "co-trimoxazole") },
            { "crizanlizumab", new ValueWithNote("37497670", "crizanlizumab") },
            { "cyclizine lactate", new ValueWithNote("19135874", "cyclizine lactate") },
            { "cyclizine", new ValueWithNote("909358", "cyclizine") },
            { "cyclophosphamide", new ValueWithNote("1310317", "cyclophosphamide") },
            { "cytarabine", new ValueWithNote("1311078", "cytarabine") },
            { "dabrafenib", new ValueWithNote("43532299", "dabrafenib") },
            { "dacarbazine", new ValueWithNote("1311409", "dacarbazine") },
            { "dapsone", new ValueWithNote("1711759", "dapsone") },
            { "daratumumab", new ValueWithNote("35605744", "daratumumab") },
            { "darbepoetin alfa", new ValueWithNote("1304643", "darbepoetin alfa") },
            { "darolutamide", new ValueWithNote("1361291", "darolutamide") },
            { "dasatinib", new ValueWithNote("1358436", "dasatinib") },
            { "datopotamab deruxtecan", new ValueWithNote("36857648", "datopotamab deruxtecan") },
            { "daunorubicin", new ValueWithNote("1311799", "daunorubicin") },
            { "denosumab", new ValueWithNote("40222444", "denosumab") },
            { "dexamethasone", new ValueWithNote("1518254", "dexamethasone") },
            { "dexrazoxane", new ValueWithNote("1353011", "dexrazoxane") },
            { "difflam", new ValueWithNote("40033209", "difflam") },
            { "docetaxel", new ValueWithNote("1315942", "docetaxel") },
            { "domvanalimab", new ValueWithNote("36851459", "domvanalimab") },
            { "doxorubicin pegylated liposomal", new ValueWithNote("902725", "doxorubicin pegylated liposomal") },
            { "doxorubicin", new ValueWithNote("1338512", "doxorubicin") },
            { "durvalumab", new ValueWithNote("1594034", "durvalumab") },
            { "e45", new ValueWithNote("40756336", "e45") },
            { "elranatamab", new ValueWithNote("746391", "elranatamab") },
            { "encorafenib", new ValueWithNote("1559914", "encorafenib") },
            { "enfortumab vedotin", new ValueWithNote("37498707", "enfortumab vedotin") },
            { "enzalutamide", new ValueWithNote("42900250", "enzalutamide") },
            { "epirubicin hydrochloride", new ValueWithNote("19026849", "epirubicin hydrochloride") },
            { "epoetin zeta", new ValueWithNote("21014076", "epoetin zeta") },
            { "eribulin", new ValueWithNote("40230712", "eribulin") },
            { "etoposide", new ValueWithNote("1350504", "etoposide") },
            { "everolimus", new ValueWithNote("19011440", "everolimus") },
            { "exemestane", new ValueWithNote("1398399", "exemestane") },
            { "ezabenlimab", new ValueWithNote("36852576", "ezabenlimab") },
            { "famotidine", new ValueWithNote("953076", "famotidine") },
            { "fedratinib", new ValueWithNote("1361614", "fedratinib") },
            { "fenofibrate", new ValueWithNote("1551803", "fenofibrate") },
            { "ferinject", new ValueWithNote("21017287", "ferinject") },
            { "filgrastim", new ValueWithNote("1304850", "filgrastim") },
            { "fluconazole", new ValueWithNote("1754994", "fluconazole") },
            { "fludarabine", new ValueWithNote("1395557", "fludarabine") },
            { "fluorouracil", new ValueWithNote("955632", "fluorouracil") },
            { "fosaprepitant", new ValueWithNote("35605594", "fosaprepitant") },
            { "fulvestrant", new ValueWithNote("1304044", "fulvestrant") },
            { "furosemide", new ValueWithNote("956874", "furosemide") },
            { "gemcitabine", new ValueWithNote("1314924", "gemcitabine") },
            { "gemtuzumab ozogamicin", new ValueWithNote("42799711", "gemtuzumab ozogamicin") },
            { "glofitamab", new ValueWithNote("1201501", "glofitamab") },
            { "glucose", new ValueWithNote("1560524", "glucose") },
            { "goserelin", new ValueWithNote("1366310", "goserelin") },
            { "hmbd-001", new ValueWithNote("1254204", "nezutatug") },
            { "hydrocortisone (as sodium succinate", new ValueWithNote("19055140", "hydrocortisone sodium succinate") },
            { "hydrocortisone na succinate", new ValueWithNote("975125", "hydrocortisone") },
            { "hydroxocobalamin", new ValueWithNote("1377023", "hydroxocobalamin") },
            { "hydroxycarbamide", new ValueWithNote("1377141", "hydroxyurea") },
            { "iberdomide", new ValueWithNote("36854679", "iberdomide") },
            { "ibrutinib", new ValueWithNote("44507848", "ibrutinib") },
            { "ibuprofen", new ValueWithNote("1177480", "ibuprofen") },
            { "idarubicin hydrochloride", new ValueWithNote("19132979", "idarubicin hydrochloride") },
            { "idelalisib", new ValueWithNote("45776944", "idelalisib") },
            { "ifosfamide", new ValueWithNote("19078187", "ifosfamide") },
            { "imatinib", new ValueWithNote("1304107", "imatinib") },
            { "imc-f106c", new ValueWithNote("1253676", "brenetafusp") },
            { "imetelstat sodium", new ValueWithNote("1734582", "imetelstat sodium") },
            { "imgn632", new ValueWithNote("36859012", "pivekimab sunirine") },
            { "inotuzumab ozogamicin", new ValueWithNote("794068", "inotuzumab ozogamicin") },
            { "ipilimumab", new ValueWithNote("40238188", "ipilimumab") },
            { "irinotecan hydrochloride", new ValueWithNote("19017121", "irinotecan hydrochloride") },
            { "isatuximab", new ValueWithNote("37498969", "isatuximab") },
            { "isavuconazole", new ValueWithNote("35606695", "isavuconazole") },
            { "isis 702843", new ValueWithNote("36838992", "sapablursen") },
            { "ixazomib", new ValueWithNote("35606214", "ixazomib") },
            { "ky1044", new ValueWithNote("36823338", "alomfilimab") },
            { "lamivudine", new ValueWithNote("1704183", "lamivudine") },
            { "lenalidomide", new ValueWithNote("19026972", "lenalidomide") },
            { "lenograstim", new ValueWithNote("19009705", "lenograstim") },
            { "lenvatinib", new ValueWithNote("46221433", "lenvatinib") },
            { "lenzilumab", new ValueWithNote("36858275", "lenzilumab") },
            { "letrozole", new ValueWithNote("1315946", "letrozole") },
            { "levofloxacin", new ValueWithNote("1742253", "levofloxacin") },
            { "lomustine", new ValueWithNote("1391846", "lomustine") },
            { "loperamide", new ValueWithNote("991876", "loperamide") },
            { "loratadine", new ValueWithNote("1107830", "loratadine") },
            { "lorazepam", new ValueWithNote("791967", "lorazepam") },
            { "lorlatinib", new ValueWithNote("35201733", "lorlatinib") },
            { "loxo-305", new ValueWithNote("36829506", "pirtobrutinib") },
            { "lutetium 177", new ValueWithNote("963949", "lutetium lu 177 dotatate") },
            { "macrogol compound", new ValueWithNote("40750519", "bicarbonate ion / polyethylene glycol 3350 / potassium / sodium oral powder") },
            { "magnesium sulfate", new ValueWithNote("19093848", "magnesium sulfate") },
            { "magnesium sulphate", new ValueWithNote("19093848", "magnesium sulfate") },
            { "mannitol", new ValueWithNote("994058", "mannitol") },
            { "melphalan", new ValueWithNote("1301267", "melphalan") },
            { "mercaptopurine", new ValueWithNote("1436650", "mercaptopurine") },
            { "mesna", new ValueWithNote("1354698", "mesna") },
            { "methotrexate", new ValueWithNote("1305058", "methotrexate") },
            { "methylprednisolone sodium succ", new ValueWithNote("19026798", "methylprednisolone sodium succinate") },
            { "methylprednisolone", new ValueWithNote("1506270", "methylprednisolone") },
            { "methylthioninium chloride", new ValueWithNote("905518", "methylene blue") },
            { "metoclopramide", new ValueWithNote("906780", "metoclopramide") },
            { "midostaurin", new ValueWithNote("1594003", "midostaurin") },
            { "mifamurtide", new ValueWithNote("21014035", "mifamurtide") },
            { "mitomycin", new ValueWithNote("1389036", "mitomycin") },
            { "mitotane", new ValueWithNote("1309161", "mitotane") },
            { "mobocertinib", new ValueWithNote("701915", "mobocertinib") },
            { "mogamulizumab", new ValueWithNote("35200202", "mogamulizumab") },
            { "momelotinib", new ValueWithNote("746600", "momelotinib") },
            { "montelukast", new ValueWithNote("1154161", "montelukast") },
            { "mosunetuzumab", new ValueWithNote("1301307", "mosunetuzumab") },
            { "mycophenolate mofetil", new ValueWithNote("19003999", "mycophenolate mofetil") },
            { "navitoclax", new ValueWithNote("36863201", "navitoclax") },
            { "nemvaleukin alfa", new ValueWithNote("36854062", "nemvaleukin alfa") },
            { "nilotinib", new ValueWithNote("1394023", "nilotinib") },
            { "niraparib", new ValueWithNote("1593861", "niraparib") },
            { "nis793", new ValueWithNote("36862643", "nis-793") },
            { "nivolumab", new ValueWithNote("45892628", "nivolumab") },
            { "nuc-7738", new ValueWithNote("1254555", "cordycepin 5'-monophosphate") },
            { "nx-5948", new ValueWithNote("1253305", "nx-5948 free base") },
            { "obinutuzumab", new ValueWithNote("44507676", "obinutuzumab") },
            { "olaparib", new ValueWithNote("45892579", "olaparib") },
            { "omeprazole", new ValueWithNote("923645", "omeprazole") },
            { "ondansetron", new ValueWithNote("1000560", "ondansetron") },
            { "osimertinib", new ValueWithNote("35605522", "osimertinib") },
            { "oxaliplatin", new ValueWithNote("1318011", "oxaliplatin") },
            { "oxytetracycline", new ValueWithNote("925952", "oxytetracycline") },
            { "paclitaxel albumin bound", new ValueWithNote("902729", "paclitaxel protein-bound") },
            { "paclitaxel", new ValueWithNote("1378382", "paclitaxel") },
            { "palbociclib", new ValueWithNote("45892075", "palbociclib") },
            { "pamidronate disodium", new ValueWithNote("19007069", "pamidronate disodium") },
            { "panitumumab", new ValueWithNote("19100985", "panitumumab") },
            { "panobinostat", new ValueWithNote("46221435", "panobinostat") },
            { "paracetamol", new ValueWithNote("40814161", "paracetamol l") },
            { "pazopanib", new ValueWithNote("40167554", "pazopanib") },
            { "peg-asparaginase", new ValueWithNote("1326481", "pegaspargase") },
            { "pembrolizumab", new ValueWithNote("45775965", "pembrolizumab") },
            { "pemetrexed", new ValueWithNote("1304919", "pemetrexed") },
            { "pentamidine isetionate", new ValueWithNote("19130479", "pentamidine isethionate") },
            { "pertuzumab", new ValueWithNote("42801287", "pertuzumab") },
            { "pirtobrutinib", new ValueWithNote("1301683", "pirtobrutinib") },
            { "plerixafor", new ValueWithNote("19017581", "plerixafor") },
            { "polatuzumab vedotin", new ValueWithNote("1396729", "polatuzumab vedotin") },
            { "pomalidomide", new ValueWithNote("43014237", "pomalidomide") },
            { "ponatinib", new ValueWithNote("43013182", "ponatinib") },
            { "potassium chloride", new ValueWithNote("19049105", "potassium chloride") },
            { "prednisolone", new ValueWithNote("1550557", "prednisolone") },
            { "prednisone", new ValueWithNote("1551099", "prednisone") },
            { "procarbazine", new ValueWithNote("1351779", "procarbazine") },
            { "prochlorperazine", new ValueWithNote("752061", "prochlorperazine") },
            { "radium 223 (xofigo)", new ValueWithNote("45775578", "radium") },
            { "raltitrexed", new ValueWithNote("19038536", "raltitrexed") },
            { "ramucirumab", new ValueWithNote("44818489", "ramucirumab") },
            { "ranitidine", new ValueWithNote("961047", "ranitidine") },
            { "rasburicase", new ValueWithNote("1304565", "rasburicase") },
            { "regorafenib", new ValueWithNote("42903460", "regorafenib") },
            { "ribociclib", new ValueWithNote("1592911", "ribociclib") },
            { "rituximab", new ValueWithNote("1314273", "rituximab") },
            { "romidepsin", new ValueWithNote("40168385", "romidepsin") },
            { "ropeginterferon alfa-2b", new ValueWithNote("702407", "ropeginterferon alfa-2b") },
            { "rucaparib", new ValueWithNote("1718850", "rucaparib") },
            { "runimotamab", new ValueWithNote("36857285", "runimotamab") },
            { "ruxolitinib", new ValueWithNote("40244464", "ruxolitinib") },
            { "sacituzumab govitecan", new ValueWithNote("1145485", "sacituzumab govitecan") },
            { "samuraciclib", new ValueWithNote("36851482", "samuraciclib") },
            { "selpercatinib", new ValueWithNote("1145791", "selpercatinib") },
            { "siltuximab", new ValueWithNote("44818461", "siltuximab") },
            { "sodium bicarbonate", new ValueWithNote("939506", "sodium bicarbonate") },
            { "sodium chloride", new ValueWithNote("967823", "sodium chloride") },
            { "sorafenib", new ValueWithNote("1363387", "sorafenib") },
            { "sotorasib", new ValueWithNote("1536963", "sotorasib") },
            { "spartalizumab", new ValueWithNote("36860836", "spartalizumab") },
            { "st101", new ValueWithNote("36853978", "st-101") },
            { "streptozocin", new ValueWithNote("19136210", "streptozocin") },
            { "sunitinib malate", new ValueWithNote("19123411", "sunitinib malate") },
            { "talimogene laherparepvec", new ValueWithNote("35605133", "talimogene laherparepvec") },
            { "trametinib", new ValueWithNote("43532497", "trametinib") },
            { "trastuzumab deruxtecan", new ValueWithNote("37498192", "trastuzumab deruxtecan") },
            { "trastuzumab emtansine (kadcyla)", new ValueWithNote("1387104", "trastuzumab") },
            { "trastuzumab emtansine", new ValueWithNote("43525787", "ado-trastuzumab emtansine") },
            { "trastuzumab", new ValueWithNote("1387104", "trastuzumab") },
            { "tretinoin", new ValueWithNote("903643", "tretinoin") },
            { "trifluridine with tipiracil", new ValueWithNote("36248234", "tipiracil / trifluridine oral product") },
            { "tucatinib", new ValueWithNote("1145571", "tucatinib") },
            { "ucb6114", new ValueWithNote("36852947", "ginisortamab") },
            { "venetoclax", new ValueWithNote("35604205", "venetoclax") },
            { "vimseltinib", new ValueWithNote("36860563", "vimseltinib") },
            { "vinblastine sulphate", new ValueWithNote("19010966", "vinblastine sulfate") },
            { "vincristine sulphate", new ValueWithNote("19010967", "vincristine sulfate") },
            { "vinorelbine", new ValueWithNote("1343346", "vinorelbine") },
            { "xentuzumab", new ValueWithNote("36863086", "xentuzumab") },
            { "zanubrutinib", new ValueWithNote("37497691", "zanubrutinib") },
            { "zimberelimab", new ValueWithNote("36863769", "zimberelimab") },
            { "zoledronic acid", new ValueWithNote("1524674", "zoledronic acid") },
            { "temozolomide", new ValueWithNote("1341149", "temozolomide") },
            { "thalidomide", new ValueWithNote("19137042", "thalidomide") },
            { "trabectedin", new ValueWithNote("35603017", "trabectedin") },
            { "thiotepa", new ValueWithNote("19137385", "thiotepa") },
            { "topotecan", new ValueWithNote("1378509", "topotecan") },
            { "tivozanib", new ValueWithNote("36026750", "tivozanib") },
            { "tocilizumab", new ValueWithNote("40171288", "tocilizumab") },
            { "tislelizumab", new ValueWithNote("42609339", "tislelizumab") },
            { "bms-986213 / nivolumab", new ValueWithNote("779243", "nivolumab / relatlimab injection") },
            { "pertuzumab / trastuzumab", new ValueWithNote("1075655", "Pertuzumab- and trastuzumab-containing product") },

            // placebo

            { "aspirin 100mg/ 300mg/placebo", new ValueWithNote("19047135", "placebo") },
            { "azacitidine / placebo", new ValueWithNote("19047135", "placebo") },
            { "durvalumab / placebo", new ValueWithNote("19047135", "placebo") },
            { "incmga00012 / placebo", new ValueWithNote("19047135", "placebo") },
            { "magrolimab / placebo", new ValueWithNote("19047135", "placebo") },
            { "navitoclax/placebo", new ValueWithNote("19047135", "placebo") },
            { "nis793 / placebo", new ValueWithNote("19047135", "placebo") },
            { "roxadustat / placebo", new ValueWithNote("19047135", "placebo") },

            // no mappings

            // { "stem cell infusion", new ValueWithNote("0", "") },
            // { "stp938", new ValueWithNote("0", "") },
            // { "sonotran particles", new ValueWithNote("0", "") },
            // { "h2 antagonist - prescribe using sup", new ValueWithNote("0", "") },
            // { "gastric protection-prescribe using ", new ValueWithNote("0", "") },
            // { "amphotericin encapsulated in liposo", new ValueWithNote("0", "") },
            // { "aromatase inhibitor reminder - pres", new ValueWithNote("0", "") },
            // { "bi 1703880", new ValueWithNote("0", "") },
            // { "blueteq registration requirements -", new ValueWithNote("0", "") },
            // { "bone marrow/stem cell", new ValueWithNote("0", "") },
            // { "bsa calculation for sact", new ValueWithNote("0", "") },
            // { "bsa for sact and renal calculations", new ValueWithNote("0", "") },
            // { "calcium carbonate              with", new ValueWithNote("0", "") },
            // { "cmv, hsv & vzv prophylaxis", new ValueWithNote("0", "") },
            // { "cord cell infusion", new ValueWithNote("0", "") },
            // { "imm60", new ValueWithNote("0", "") },
            // { "irradiated blood products required", new ValueWithNote("0", "") },
            // { "jnj-75276617", new ValueWithNote("0", "") },
            // { "mdx-124", new ValueWithNote("0", "") },
            // { "must be ordered with methotrexate i", new ValueWithNote("0", "") },
            // { "ng-350a", new ValueWithNote("0", "ng-350a is a next-generation blood-stable adenoviral vector") },
            // { "oral cryotherapy", new ValueWithNote("0", "") },
            // { "oral hydration", new ValueWithNote("0", "") },
            // { "plx2853", new ValueWithNote("0", "") },
            // { "proton pump inhibitor", new ValueWithNote("0", "") },
            // { "red cell phenotype/genotype ï¿½ pre t", new ValueWithNote("0", "") },
            // { "red cell phenotype/genotype â€“ pre t", new ValueWithNote("0", "") },
            // { "rp2", new ValueWithNote("0", "") },
            // { "rp3", new ValueWithNote("0", "") },
            // { "rso-021", new ValueWithNote("0", "") },
            // { "scib1", new ValueWithNote("0", "") }
        };

    public string[] ColumnNotes =>
    [
        "[Athena Drug Concepts](https://athena.ohdsi.org/search-terms/terms?standardConcept=Standard&domain=Drug&vocabulary=RxNorm&vocabulary=RxNorm+Extension&invalidReason=Valid&page=1&pageSize=15&query=)",
        "[placebo forum discussion](https://forums.ohdsi.org/t/how-would-you-map-drug-name-placebo-clinical-trial/15622/2)"
    ];
}