using OmopTransformer.Annotations;

namespace OmopTransformer.Transformation;

[Description("SACT Drug lookup")]
internal class SactDrugLookup : ILookup
{
    public Dictionary<string, ValueWithNote> Mappings { get; } =
        new()
        {
            { "ABEMACICLIB", new ValueWithNote("792649", "abemaciclib") },
            { "ABIRATERONE ACETATE", new ValueWithNote("46274231", "abiraterone acetate") },
            { "Abiraterone", new ValueWithNote("40239056", "abiraterone") },
            { "ACALABRUTINIB", new ValueWithNote("792764", "acalabrutinib") },
            { "ACICLOVIR", new ValueWithNote("42907410", "VACICLOVIR") },
            { "ALECTINIB", new ValueWithNote("35604657", "alectinib") },
            { "ALEMTUZUMAB", new ValueWithNote("1312706", "alemtuzumab") },
            { "ALLOPURINOL", new ValueWithNote("1167322", "allopurinol") },
            { "ALPELISIB", new ValueWithNote("1396423", "alpelisib") },
            { "APALUTAMIDE", new ValueWithNote("963987", "apalutamide") },
            { "APREPITANT", new ValueWithNote("936748", "aprepitant") },
            { "ARSENIC TRIOXIDE", new ValueWithNote("1333379", "arsenic trioxide") },
            { "Asciminib", new ValueWithNote("702133", "asciminib") },
            { "ATEZOLIZUMAB", new ValueWithNote("42629079", "atezolizumab") },
            { "ATROPINE SULPHATE", new ValueWithNote("19018119", "atropine sulfate") },
            { "AVAPRITINIB", new ValueWithNote("37498468", "avapritinib") },
            { "AVELUMAB", new ValueWithNote("1593273", "avelumab") },
            { "AXICABTAGENE CILOLEUCEL", new ValueWithNote("792844", "axicabtagene ciloleucel") },
            { "AXITINIB", new ValueWithNote("42709322", "axitinib") },
            { "AZACITIDINE", new ValueWithNote("1314865", "azacitidine") },
            { "AZD4573", new ValueWithNote("36856884", "AZD-4573") },
            { "Belantamab mafodotin", new ValueWithNote("37002419", "belantamab mafodotin") },
            { "BENDAMUSTINE", new ValueWithNote("19015523", "bendamustine") },
            { "BEVACIZUMAB", new ValueWithNote("1397141", "bevacizumab") },
            { "BEXAROTENE", new ValueWithNote("1389888", "bexarotene") },
            { "BINIMETINIB", new ValueWithNote("1559930", "binimetinib") },
            { "BLEOMYCIN SULPHATE", new ValueWithNote("19018330", "bleomycin sulfate") },
            { "BLINATUMOMAB", new ValueWithNote("45892531", "blinatumomab") },
            { "BORTEZOMIB", new ValueWithNote("1336825", "bortezomib") },
            { "Bosutinib", new ValueWithNote("42900401", "bosutinib") },
            { "BRENTUXIMAB VEDOTIN", new ValueWithNote("40241969", "brentuximab vedotin") },
            { "BRIGATINIB", new ValueWithNote("1594187", "brigatinib") },
            { "BUSULFAN", new ValueWithNote("1333357", "busulfan") },
            { "CABAZITAXEL", new ValueWithNote("40222431", "cabazitaxel") },
            { "CABOZANTINIB", new ValueWithNote("43012292", "cabozantinib") },
            { "CALCIUM LEVOFOLINATE", new ValueWithNote("36256127", "Calcium levofolinate") },
            { "CAPECITABINE", new ValueWithNote("1337620", "capecitabine") },
            { "CARBOPLATIN", new ValueWithNote("1344905", "carboplatin") },
            { "CARFILZOMIB", new ValueWithNote("42873638", "carfilzomib") },
            { "CARMUSTINE", new ValueWithNote("1350066", "carmustine") },
            { "Cediranib", new ValueWithNote("36859905", "CEDIRANIB") },
            { "CEMIPLIMAB", new ValueWithNote("35200783", "cemiplimab") },
            { "Ceralasertib", new ValueWithNote("36854241", "CERALASERTIB") },
            { "CETIRIZINE", new ValueWithNote("1149196", "cetirizine") },
            { "CETUXIMAB", new ValueWithNote("1315411", "cetuximab") },
            { "CHLORAMBUCIL", new ValueWithNote("1390051", "chlorambucil") },
            { "CHLORPHENAMINE", new ValueWithNote("19049707", "chlorphenoxamine") },
            { "CISPLATIN", new ValueWithNote("1397599", "cisplatin") },
            { "CLADRIBINE", new ValueWithNote("19054825", "cladribine") },
            { "CO-TRIMOXAZOLE", new ValueWithNote("21018085", "Co-trimoxazole") },
            { "CRIZANLIZUMAB", new ValueWithNote("37497670", "crizanlizumab") },
            { "CYCLIZINE LACTATE", new ValueWithNote("19135874", "cyclizine lactate") },
            { "CYCLIZINE", new ValueWithNote("909358", "cyclizine") },
            { "CYCLOPHOSPHAMIDE", new ValueWithNote("1310317", "cyclophosphamide") },
            { "CYTARABINE", new ValueWithNote("1311078", "cytarabine") },
            { "Dabrafenib", new ValueWithNote("43532299", "dabrafenib") },
            { "DACARBAZINE", new ValueWithNote("1311409", "dacarbazine") },
            { "DAPSONE", new ValueWithNote("1711759", "dapsone") },
            { "DARATUMUMAB", new ValueWithNote("35605744", "daratumumab") },
            { "DARBEPOETIN ALFA", new ValueWithNote("1304643", "darbepoetin alfa") },
            { "DAROLUTAMIDE", new ValueWithNote("1361291", "darolutamide") },
            { "DASATINIB", new ValueWithNote("1358436", "dasatinib") },
            { "Datopotamab deruxtecan", new ValueWithNote("36857648", "DATOPOTAMAB DERUXTECAN") },
            { "DAUNORUBICIN", new ValueWithNote("1311799", "daunorubicin") },
            { "DENOSUMAB", new ValueWithNote("40222444", "denosumab") },
            { "DEXAMETHASONE", new ValueWithNote("1518254", "dexamethasone") },
            { "DEXRAZOXANE", new ValueWithNote("1353011", "dexrazoxane") },
            { "DIFFLAM", new ValueWithNote("40033209", "Difflam") },
            { "DOCETAXEL", new ValueWithNote("1315942", "docetaxel") },
            { "Domvanalimab", new ValueWithNote("36851459", "DOMVANALIMAB") },
            { "DOXORUBICIN PEGYLATED LIPOSOMAL", new ValueWithNote("902725", "Doxorubicin pegylated liposomal") },
            { "DOXORUBICIN", new ValueWithNote("1338512", "doxorubicin") },
            { "DURVALUMAB", new ValueWithNote("1594034", "durvalumab") },
            { "E45", new ValueWithNote("40756336", "E45") },
            { "Elranatamab", new ValueWithNote("746391", "elranatamab") },
            { "ENCORAFENIB", new ValueWithNote("1559914", "encorafenib") },
            { "Enfortumab vedotin", new ValueWithNote("37498707", "enfortumab vedotin") },
            { "ENZALUTAMIDE", new ValueWithNote("42900250", "enzalutamide") },
            { "EPIRUBICIN HYDROCHLORIDE", new ValueWithNote("19026849", "epirubicin hydrochloride") },
            { "EPOETIN ZETA", new ValueWithNote("21014076", "Epoetin zeta") },
            { "ERIBULIN", new ValueWithNote("40230712", "eribulin") },
            { "ETOPOSIDE", new ValueWithNote("1350504", "etoposide") },
            { "EVEROLIMUS", new ValueWithNote("19011440", "everolimus") },
            { "EXEMESTANE", new ValueWithNote("1398399", "exemestane") },
            { "Ezabenlimab", new ValueWithNote("36852576", "EZABENLIMAB") },
            { "FAMOTIDINE", new ValueWithNote("953076", "famotidine") },
            { "FEDRATINIB", new ValueWithNote("1361614", "fedratinib") },
            { "FENOFIBRATE", new ValueWithNote("1551803", "fenofibrate") },
            { "FERINJECT", new ValueWithNote("21017287", "Ferinject") },
            { "FILGRASTIM", new ValueWithNote("1304850", "filgrastim") },
            { "FLUCONAZOLE", new ValueWithNote("1754994", "fluconazole") },
            { "FLUDARABINE", new ValueWithNote("1395557", "fludarabine") },
            { "FLUOROURACIL", new ValueWithNote("955632", "fluorouracil") },
            { "FOSAPREPITANT", new ValueWithNote("35605594", "fosaprepitant") },
            { "FULVESTRANT", new ValueWithNote("1304044", "fulvestrant") },
            { "FUROSEMIDE", new ValueWithNote("956874", "furosemide") },
            { "GEMCITABINE", new ValueWithNote("1314924", "gemcitabine") },
            { "GEMTUZUMAB OZOGAMICIN", new ValueWithNote("42799711", "gemtuzumab ozogamicin") },
            { "Glofitamab", new ValueWithNote("1201501", "glofitamab") },
            { "GLUCOSE", new ValueWithNote("1560524", "glucose") },
            { "GOSERELIN", new ValueWithNote("1366310", "goserelin") },
            { "HYDROCORTISONE (AS SODIUM SUCCINATE", new ValueWithNote("19055140", "hydrocortisone sodium succinate") },
            { "HYDROXOCOBALAMIN", new ValueWithNote("1377023", "hydroxocobalamin") },
            { "Iberdomide", new ValueWithNote("36854679", "IBERDOMIDE") },
            { "IBRUTINIB", new ValueWithNote("44507848", "ibrutinib") },
            { "IBUPROFEN", new ValueWithNote("1177480", "ibuprofen") },
            { "IDARUBICIN HYDROCHLORIDE", new ValueWithNote("19132979", "idarubicin hydrochloride") },
            { "Idelalisib", new ValueWithNote("45776944", "idelalisib") },
            { "IFOSFAMIDE", new ValueWithNote("19078187", "ifosfamide") },
            { "IMATINIB", new ValueWithNote("1304107", "imatinib") },
            { "Imetelstat Sodium", new ValueWithNote("1734582", "imetelstat sodium") },
            { "INOTUZUMAB OZOGAMICIN", new ValueWithNote("794068", "inotuzumab ozogamicin") },
            { "IPILIMUMAB", new ValueWithNote("40238188", "ipilimumab") },
            { "IRINOTECAN HYDROCHLORIDE", new ValueWithNote("19017121", "irinotecan hydrochloride") },
            { "ISATUXIMAB", new ValueWithNote("37498969", "isatuximab") },
            { "ISAVUCONAZOLE", new ValueWithNote("35606695", "isavuconazole") },
            { "IXAZOMIB", new ValueWithNote("35606214", "ixazomib") },
            { "LAMIVUDINE", new ValueWithNote("1704183", "lamivudine") },
            { "LENALIDOMIDE", new ValueWithNote("19026972", "lenalidomide") },
            { "LENOGRASTIM", new ValueWithNote("19009705", "lenograstim") },
            { "LENVATINIB", new ValueWithNote("46221433", "lenvatinib") },
            { "Lenzilumab", new ValueWithNote("36858275", "LENZILUMAB") },
            { "LETROZOLE", new ValueWithNote("1315946", "letrozole") },
            { "LEVOFLOXACIN", new ValueWithNote("1742253", "levofloxacin") },
            { "LOMUSTINE", new ValueWithNote("1391846", "lomustine") },
            { "LOPERAMIDE", new ValueWithNote("991876", "loperamide") },
            { "LORATADINE", new ValueWithNote("1107830", "loratadine") },
            { "LORAZEPAM", new ValueWithNote("791967", "lorazepam") },
            { "LORLATINIB", new ValueWithNote("35201733", "lorlatinib") },
            { "MAGNESIUM SULFATE", new ValueWithNote("19093848", "magnesium sulfate") },
            { "MAGNESIUM SULPHATE", new ValueWithNote("19093848", "magnesium sulfate") },
            { "MANNITOL", new ValueWithNote("994058", "mannitol") },
            { "MELPHALAN", new ValueWithNote("1301267", "melphalan") },
            { "MERCAPTOPURINE", new ValueWithNote("1436650", "mercaptopurine") },
            { "MESNA", new ValueWithNote("1354698", "mesna") },
            { "METHOTREXATE", new ValueWithNote("1305058", "methotrexate") },
            { "METHYLPREDNISOLONE SODIUM SUCC", new ValueWithNote("19026798", "methylprednisolone sodium succinate") },
            { "METHYLPREDNISOLONE", new ValueWithNote("1506270", "methylprednisolone") },
            { "METOCLOPRAMIDE", new ValueWithNote("906780", "metoclopramide") },
            { "MIDOSTAURIN", new ValueWithNote("1594003", "midostaurin") },
            { "MIFAMURTIDE", new ValueWithNote("21014035", "Mifamurtide") },
            { "MITOMYCIN", new ValueWithNote("1389036", "mitomycin") },
            { "MITOTANE", new ValueWithNote("1309161", "mitotane") },
            { "MOBOCERTINIB", new ValueWithNote("701915", "mobocertinib") },
            { "MOGAMULIZUMAB", new ValueWithNote("35200202", "mogamulizumab") },
            { "Momelotinib", new ValueWithNote("746600", "momelotinib") },
            { "MONTELUKAST", new ValueWithNote("1154161", "montelukast") },
            { "Mosunetuzumab", new ValueWithNote("1301307", "mosunetuzumab") },
            { "MYCOPHENOLATE MOFETIL", new ValueWithNote("19003999", "mycophenolate mofetil") },
            { "Navitoclax", new ValueWithNote("36863201", "NAVITOCLAX") },
            { "Nemvaleukin Alfa", new ValueWithNote("36854062", "NEMVALEUKIN ALFA") },
            { "NILOTINIB", new ValueWithNote("1394023", "nilotinib") },
            { "NIRAPARIB", new ValueWithNote("1593861", "niraparib") },
            { "NIS793", new ValueWithNote("36862643", "NIS-793") },
            { "NIVOLUMAB", new ValueWithNote("45892628", "nivolumab") },
            { "OBINUTUZUMAB", new ValueWithNote("44507676", "obinutuzumab") },
            { "OLAPARIB", new ValueWithNote("45892579", "olaparib") },
            { "OMEPRAZOLE", new ValueWithNote("923645", "omeprazole") },
            { "ONDANSETRON", new ValueWithNote("1000560", "ondansetron") },
            { "OSIMERTINIB", new ValueWithNote("35605522", "osimertinib") },
            { "OXALIPLATIN", new ValueWithNote("1318011", "oxaliplatin") },
            { "OXYTETRACYCLINE", new ValueWithNote("925952", "oxytetracycline") },
            { "PACLITAXEL", new ValueWithNote("1378382", "paclitaxel") },
            { "PALBOCICLIB", new ValueWithNote("45892075", "palbociclib") },
            { "PAMIDRONATE DISODIUM", new ValueWithNote("19007069", "pamidronate disodium") },
            { "PANITUMUMAB", new ValueWithNote("19100985", "panitumumab") },
            { "PANOBINOSTAT", new ValueWithNote("46221435", "panobinostat") },
            { "PARACETAMOL", new ValueWithNote("40814161", "Paracetamol L") },
            { "PAZOPANIB", new ValueWithNote("40167554", "pazopanib") },
            { "PEMBROLIZUMAB", new ValueWithNote("45775965", "pembrolizumab") },
            { "PEMETREXED", new ValueWithNote("1304919", "pemetrexed") },
            { "PENTAMIDINE ISETIONATE", new ValueWithNote("19130479", "pentamidine isethionate") },
            { "Pertuzumab", new ValueWithNote("42801287", "pertuzumab") },
            { "Pirtobrutinib", new ValueWithNote("1301683", "pirtobrutinib") },
            { "PLERIXAFOR", new ValueWithNote("19017581", "plerixafor") },
            { "POLATUZUMAB VEDOTIN", new ValueWithNote("1396729", "polatuzumab vedotin") },
            { "POMALIDOMIDE", new ValueWithNote("43014237", "pomalidomide") },
            { "PONATINIB", new ValueWithNote("43013182", "ponatinib") },
            { "POTASSIUM CHLORIDE", new ValueWithNote("19049105", "potassium chloride") },
            { "PREDNISOLONE", new ValueWithNote("1550557", "prednisolone") },
            { "Prednisone", new ValueWithNote("1551099", "prednisone") },
            { "PROCARBAZINE", new ValueWithNote("1351779", "procarbazine") },
            { "PROCHLORPERAZINE", new ValueWithNote("752061", "prochlorperazine") },
            { "RALTITREXED", new ValueWithNote("19038536", "raltitrexed") },
            { "RAMUCIRUMAB", new ValueWithNote("44818489", "ramucirumab") },
            { "RANITIDINE", new ValueWithNote("961047", "ranitidine") },
            { "RASBURICASE", new ValueWithNote("1304565", "rasburicase") },
            { "REGORAFENIB", new ValueWithNote("42903460", "regorafenib") },
            { "RIBOCICLIB", new ValueWithNote("1592911", "ribociclib") },
            { "RITUXIMAB", new ValueWithNote("1314273", "rituximab") },
            { "Romidepsin", new ValueWithNote("40168385", "romidepsin") },
            { "ROPEGINTERFERON ALFA-2B", new ValueWithNote("702407", "ropeginterferon alfa-2b") },
            { "RUCAPARIB", new ValueWithNote("1718850", "rucaparib") },
            { "Runimotamab", new ValueWithNote("36857285", "RUNIMOTAMAB") },
            { "RUXOLITINIB", new ValueWithNote("40244464", "ruxolitinib") },
            { "SACITUZUMAB GOVITECAN", new ValueWithNote("1145485", "sacituzumab govitecan") },
            { "Samuraciclib", new ValueWithNote("36851482", "SAMURACICLIB") },
            { "SELPERCATINIB", new ValueWithNote("1145791", "selpercatinib") },
            { "SILTUXIMAB", new ValueWithNote("44818461", "siltuximab") },
            { "SODIUM BICARBONATE", new ValueWithNote("939506", "sodium bicarbonate") },
            { "SODIUM CHLORIDE", new ValueWithNote("967823", "sodium chloride") },
            { "SORAFENIB", new ValueWithNote("1363387", "sorafenib") },
            { "SOTORASIB", new ValueWithNote("1536963", "sotorasib") },
            { "Spartalizumab", new ValueWithNote("36860836", "SPARTALIZUMAB") },
            { "ST101", new ValueWithNote("36853978", "ST-101") },
            { "STREPTOZOCIN", new ValueWithNote("19136210", "streptozocin") },
            { "SUNITINIB MALATE", new ValueWithNote("19123411", "sunitinib malate") },
            { "TALIMOGENE LAHERPAREPVEC", new ValueWithNote("35605133", "talimogene laherparepvec") },
            { "Trametinib", new ValueWithNote("43532497", "trametinib") },
            { "Trastuzumab deruxtecan", new ValueWithNote("37498192", "trastuzumab deruxtecan") },
            { "TRASTUZUMAB EMTANSINE", new ValueWithNote("43525787", "ado-trastuzumab emtansine") },
            { "TRASTUZUMAB", new ValueWithNote("1387104", "trastuzumab") },
            { "TRETINOIN", new ValueWithNote("903643", "tretinoin") },
            { "TUCATINIB", new ValueWithNote("1145571", "tucatinib") },
            { "Venetoclax", new ValueWithNote("35604205", "venetoclax") },
            { "Vimseltinib", new ValueWithNote("36860563", "VIMSELTINIB") },
            { "VINBLASTINE SULPHATE", new ValueWithNote("19010966", "vinblastine sulfate") },
            { "VINCRISTINE SULPHATE", new ValueWithNote("19010967", "vincristine sulfate") },
            { "VINORELBINE", new ValueWithNote("1343346", "vinorelbine") },
            { "Xentuzumab", new ValueWithNote("36863086", "XENTUZUMAB") },
            { "Zanubrutinib", new ValueWithNote("37497691", "zanubrutinib") },
            { "Zimberelimab", new ValueWithNote("36863769", "ZIMBERELIMAB") },
            { "ZOLEDRONIC ACID", new ValueWithNote("1524674", "zoledronic acid") }
        };

    public string[] ColumnNotes =>
    [
        "[Athena Drug Concepts](https://athena.ohdsi.org/search-terms/terms?standardConcept=Standard&domain=Drug&vocabulary=RxNorm&vocabulary=RxNorm+Extension&invalidReason=Valid&page=1&pageSize=15&query=)"
    ];
}