drop table omop_staging.cds_birth_details
drop table omop_staging.cds_critial_care_activity_codes
drop table omop_staging.cds_diagnosis
drop table omop_staging.cds_high_cost_drugs
drop table omop_staging.cds_overseas_visitors
drop table omop_staging.cds_procedure
drop table omop_staging.cds_secondary_investigations
drop table omop_staging.cds_line02
drop table omop_staging.cds_line03
drop table omop_staging.cds_line04
drop table omop_staging.cds_line05
drop table omop_staging.cds_line06
drop table omop_staging.cds_line07
drop table omop_staging.cds_line08
drop table omop_staging.cds_line09
drop table omop_staging.cds_line10
drop table omop_staging.cds_line11
drop table omop_staging.cds_line12
drop table omop_staging.cds_line01