namespace OmopTransformer.SUS.Staging.OP;

internal class OPRow
{
    public Guid MessageId { get; set; }
    public string? GeneratedRecordIdentifier { get; set; }
    public string? ReasonforAccess { get; set; }
    public string? CDStype { get; set; }
    public string? Protocolidentifier { get; set; }
    public string? UniqueCDSidentifier { get; set; }
    public string? SUSgeneratedspellID { get; set; }
    public string? Updatetype { get; set; }
    public string? BulkreplacementCDSgroup { get; set; }
    public string? Testindicator { get; set; }
    public string? Applicabledatetime { get; set; }
    public string? Censusdate { get; set; }
    public string? Extractdatetime { get; set; }
    public string? ReportperiodStartDate { get; set; }
    public string? ReportperiodEndDate { get; set; }
    public string? OrganisationcodeSenderoftransaction { get; set; }
    public string? OrganisationCodeTypeofSender { get; set; }
    public string? SubmissionDate { get; set; }
    public string? CDSInterchangeID { get; set; }
    public string? LocalPatientIdentifier { get; set; }
    public string? OrganisationCodeLocalPatientIdentifier { get; set; }
    public string? OrganisationCodeTypeLocalPatientIdentifier { get; set; }
    public string? NHSNumber { get; set; }
    public string? DateofBirth { get; set; }
    public string? CarerSupportIndicator { get; set; }
    public string? NHSNumberTraceStatus { get; set; }
    public string? WithheldIdentityReason { get; set; }
    public string? Sex { get; set; }
    public string? NameFormatCode { get; set; }
    public string? PatientName { get; set; }
    public string? PersonTitle { get; set; }
    public string? PersonGivenName { get; set; }
    public string? PersonFamilyName { get; set; }
    public string? PersonNameSuffix { get; set; }
    public string? PersonInitials { get; set; }
    public string? AddressFormatCode { get; set; }
    public string? PatientUsualAddress { get; set; }
    public string? Postcode { get; set; }
    public string? OrganisationCodeResidenceResponsibility { get; set; }
    public string? PCTofResidence { get; set; }
    public string? OrganisationCodeTypePCTofResidence { get; set; }
    public string? EthnicCategory { get; set; }
    public string? OSVClassificationatCDSActivityDate { get; set; }
    public string? ConsultantCode { get; set; }
    public string? MainSpecialtyCode { get; set; }
    public string? TreatmentFunctionCode { get; set; }
    public string? LocalSubSpecialtyCode { get; set; }
    public string? MultiProfessionalOrMultidisciplinaryIndCode { get; set; }
    public string? RehabilitationAssessmentTeamType { get; set; }
    public string? DiagnosisSchemeInUseICD { get; set; }
    public string? DiagnosisSchemeInUseRead { get; set; }
    public string? AttendanceIdentifier { get; set; }
    public string? AdministrativeCategory { get; set; }
    public string? AttendedorDidNotAttend { get; set; }
    public string? FirstAttendance { get; set; }
    public string? MedicalStaffTypeSeeingPatient { get; set; }
    public string? OperationStatusPerAttendance { get; set; }
    public string? OutcomeofAttendance { get; set; }
    public string? AppointmentDate { get; set; }
    public string? AppointmentTime { get; set; }
    public string? ExpectedDurationOfAppointment { get; set; }
    public string? ConsultationMediumUsed { get; set; }
    public string? WaitingTimeMeasurementType { get; set; }
    public string? ActivityLocationTypeCode { get; set; }
    public string? EarliestClinicallyAppropriateDate { get; set; }
    public string? ClinicCode { get; set; }
    public string? CommissioningSerialNumber { get; set; }
    public string? NHSServiceAgreementLineNumber { get; set; }
    public string? ProviderReferenceNumber { get; set; }
    public string? CommissionerReferenceNumber { get; set; }
    public string? OrganisationCodeCodeofProvider { get; set; }
    public string? OrganisationCodeTypeCodeofProvider { get; set; }
    public string? OrganisationCodeCodeofCommissioner { get; set; }
    public string? OrganisationCodeTypeCodeofCommissioner { get; set; }
    public string? ProcedureSchemeInUseOPCS { get; set; }
    public string? ProcedureSchemeInUseRead { get; set; }
    public string? LocationClassatAttendance { get; set; }
    public string? SiteCodeofTreatment { get; set; }
    public string? OrganisationCodeTypeSiteCodeofTreatmentAtAttendance { get; set; }
    public string? GeneralMedicalPractitionerCodeofRegisteredGMP { get; set; }
    public string? PracticeCodeofRegisteredGP { get; set; }
    public string? OrganisationCodeTypeofRegisteredGP { get; set; }
    public string? PriorityType { get; set; }
    public string? ServiceTypeRequested { get; set; }
    public string? SourceofReferralForOutpatients { get; set; }
    public string? ReferralRequestReceivedDate { get; set; }
    public string? DirectAccessReferralIndicator { get; set; }
    public string? ReferrerCode { get; set; }
    public string? ReferringOrganisationCode { get; set; }
    public string? OrganisationCodeTypeofReferrer { get; set; }
    public string? LastDNAOrPatientCancelledDate { get; set; }
    public string? HRGCode { get; set; }
    public string? HRGVersionNumber { get; set; }
    public string? ProcedureSchemeInUse { get; set; }
    public string? DominantGroupingVariableProcedure { get; set; }
    public string? CoreHRG { get; set; }
    public string? HRGVersionCalculated { get; set; }
    public string? SUSHRG { get; set; }
    public string? UniqueBookingReferenceNumberConverted { get; set; }
    public string? PatientPathwayIdentifier { get; set; }
    public string? OrganisationCodePatientPathwayIdentifierIssuer { get; set; }
    public string? ReferralToTreatmentPeriodStatus { get; set; }
    public string? ReferralToTreatmentPeriodStartDate { get; set; }
    public string? ReferralToTreatmentPeriodEndDate { get; set; }
    public string? LeadCareActivityIndicator { get; set; }
    public string? AgeatCDSActivityDate { get; set; }
    public string? NHSServiceAgreementChangeDate { get; set; }
    public string? CDSActivityDate { get; set; }
    public string? EarliestReasonableOfferedDate { get; set; }
    public string? LocationType { get; set; }
    public string? XMLVersion { get; set; }
    public string? ConfidentialityCategoryDerived { get; set; }
    public string? ReferralToTreatmentLengthDerived { get; set; }
    public string? AgerangepatientderivedfromDOB { get; set; }
    public string? Areacodederivedfrompostcode { get; set; }
    public string? AttenderTypeDerived { get; set; }
    public string? CDSGroup { get; set; }
    public string? FinishedIndicator { get; set; }
    public string? PCTDerivedfromGP { get; set; }
    public string? PCTTypeDerivedfromGP { get; set; }
    public string? GPPracticeDerived { get; set; }
    public string? PCTDerivedfromderivedGPPractice { get; set; }
    public string? SHAfromGPPractice { get; set; }
    public string? SHATypefromGPPractice { get; set; }
    public string? MonthofBirth { get; set; }
    public string? ElectoralWardfrompostcode { get; set; }
    public string? PCTfrompostcode { get; set; }
    public string? PCTTypefromPostcode { get; set; }
    public string? SHAfromPostcode { get; set; }
    public string? SHATypefromPostcode { get; set; }
    public string? AreacodefromProviderPostcode { get; set; }
    public string? AgeatEndofEpisode { get; set; }
    public string? AgeatStartofEpisode { get; set; }
    public string? YearofBirth { get; set; }
    public string? CensusArea { get; set; }
    public string? Country { get; set; }
    public string? CountyCode { get; set; }
    public string? CensusED { get; set; }
    public string? EDDistrictCode { get; set; }
    public string? ElectoralWardCode { get; set; }
    public string? GORCode { get; set; }
    public string? LocalUnitaryAuthority { get; set; }
    public string? OldSHACode { get; set; }
    public string? ElectoralArea { get; set; }
    public string? PrimeRecipient { get; set; }
    public string? CopyRecipients { get; set; }
    public string? IsValidUBRN { get; set; }
    public string? UBRNOccurrenceCount { get; set; }

}