create table omop_staging.sus_APC
(
    MessageId uniqueidentifier not null,
    constraint PK_omop_staging_sus_APC_MessageId primary key clustered  (MessageId),

    GeneratedRecordIdentifier varchar(500) null,
    PBRSpellID varchar(500) null,
    ReasonForAccess varchar(500) null,
    CDSType varchar(500) null,
    ProtocolIdentifier varchar(500) null,
    UniqueCDSIdentifier varchar(500) null,
    UpdateType varchar(500) null,
    BulkReplacementCDSGroup varchar(500) null,
    TestIndicator varchar(500) null,
    ApplicableDatetime varchar(500) null,
    CensusDate varchar(500) null,
    ExtractDatetime varchar(500) null,
    ReportPeriodStartDate varchar(500) null,
    ReportPeriodEndDate varchar(500) null,
    OrganisationCodeSenderOfTransaction varchar(500) null,
    OrganisationCodeTypeofSender varchar(500) null,
    SubmissionDate varchar(500) null,
    CDSInterchangeID varchar(500) null,
    LocalPatientIdentifier varchar(500) null,
    OrganisationCodeLocalPatientIdentifier varchar(500) null,
    OrganisationCodeTypeLocalPatientIdentifier varchar(500) null,
    NHSNumber varchar(500) null,
    DateofBirth varchar(500) null,
    BirthWeight varchar(500) null,
    LiveOrStillBirth varchar(500) null,
    CarerSupportIndicator varchar(500) null,
    LegalStatusClassificationOnAdmissionPsychiatricCensusOnly varchar(500) null,
    EthnicGroup varchar(500) null,
    MaritalStatusPsychiatricCensusOnly varchar(500) null,
    NHSNumberTraceStatus varchar(500) null,
    WithheldIdentityReason varchar(500) null,
    Sex varchar(500) null,
    PregnancyTotalPreviousPregnancies varchar(500) null,
    NameFormatCode varchar(500) null,
    PatientName varchar(500) null,
    PersonTitle varchar(500) null,
    PersonGivenName varchar(500) null,
    PersonFamilyName varchar(500) null,
    PersonNameSuffix varchar(500) null,
    PersonInitials varchar(500) null,
    AddressFormatCode varchar(500) null,
    PatientUsualAddress varchar(500) null,
    Postcode varchar(500) null,
    OrganisationCodeResidenceResponsibility varchar(500) null,
    PCTofResidence varchar(500) null,
    OrganisationCodeTypePCTofResidence varchar(500) null,
    OSVClassificationatCDSActivityDate varchar(500) null,
    HospitalProviderSpellNumber varchar(500) null,
    AdministrativeCategory varchar(500) null,
    PatientClassification varchar(500) null,
    AdmissionMethodHospitalProviderSpell varchar(500) null,
    DischargeDestinationHospitalProviderSpell varchar(500) null,
    DischargeMethodHospitalProviderSpell varchar(500) null,
    SourceOfAdmissionHospitalProviderSpell varchar(500) null,
    StartDateHospitalProviderSpell varchar(500) null,
    StartTimeHospitalProviderSpell varchar(500) null,
    DischargeDateFromHospitalProviderSpell varchar(500) null,
    DischargeTimeHospitalProviderSpell varchar(500) null,
    DischargeToHospitalAtHomeServiceIndicator varchar(500) null,
    EpisodeNumber varchar(500) null,
    FirstRegularDayNightAdmission varchar(500) null,
    LastEpisodeInSpellIndicator varchar(500) null,
    NeonatalLevelOfCare varchar(500) null,
    OperationStatus varchar(500) null,
    PsychiatricPatientStatus varchar(500) null,
    StartDateConsultantEpisode varchar(500) null,
    StartTimeEpisode varchar(500) null,
    EndDateConsultantEpisode varchar(500) null,
    EndTimeEpisode varchar(500) null,
    LengthOfStayAdjustmentRehabilitation varchar(500) null,
    LengthOfStayAdjustmentSpecialistPalliativeCare varchar(500) null,
    CommissioningSerialNumber varchar(500) null,
    NHSServiceAgreementLineNumber varchar(500) null,
    ProviderReferenceNumber varchar(500) null,
    CommissionerReferenceNumber varchar(500) null,
    OrganisationCodeCodeOfProvider varchar(500) null,
    OrganisationCodeTypeOfProvider varchar(500) null,
    OrganisationCodeCodeOfCommissioner varchar(500) null,
    OrganisationCodeTypeofCommissioner varchar(500) null,
    ConsultantCode varchar(500) null,
    MainSpecialtyCode varchar(500) null,
    TreatmentFunctionCode varchar(500) null,
    LocalSubSpecialtyCode varchar(500) null,
    MultiProfessionalOrMultidisciplinaryIndCode varchar(500) null,
    RehabilitationAssessmentTeamType varchar(500) null,
    DiagnosisSchemeInUseICD varchar(500) null,
    DiagnosisSchemeInUseRead varchar(500) null,
    ProcedureSchemeInUseOPCS varchar(500) null,
    ProcedureSchemeInUseREAD varchar(500) null,
    WardCodeAtEpisodeStartDate varchar(500) null,
    WardSecurityLevelAtEpisodeStartDate varchar(500) null,
    LocationClassAtEpisodeStartDate varchar(500) null,
    SiteCodeOfTreatmentAtEpisodeStartDate varchar(500) null,
    OrganisationCodeTypeSiteCodeOfTreatmentAtStartOfEpisode varchar(500) null,
    IntendedClinicalCareIntensityAtStartOfEpisode varchar(500) null,
    AgeGroupIntendedAtStartOfEpisode varchar(500) null,
    SexOfPatientsAtStartOfEpisode varchar(500) null,
    WardDayPeriodAvailability varchar(500) null,
    WardNightPeriodAvailability varchar(500) null,
    WardCodeAtEpisodeEndDate varchar(500) null,
    WardSecurityLevelAtEpisodeEndDate varchar(500) null,
    LocationClassAtEpisodeEndDate varchar(500) null,
    SiteCodeOfTreatmentAtEpisodeEndDate varchar(500) null,
    OrganisationCodeTypeSiteCodeOfTreatmentAtEpisodeEndDate varchar(500) null,
    IntendedClinicalCareIntensityAtEpisodeEndDate varchar(500) null,
    AgeGroupIntendedAtEpisodeEndDate varchar(500) null,
    SexOfPatientsAtEpisodeEndDate varchar(500) null,
    WardDayPeriodAvailabilityAtEpisodeEndDate varchar(500) null,
    WardNightPeriodAvailabilityAtEpisodeEndDate varchar(500) null,
    GeneralMedicalPractitionerCodeofRegisteredGMP varchar(500) null,
    PracticeCodeofRegisteredGP varchar(500) null,
    OrganisationCodeTypeofRegisteredGP varchar(500) null,
    ReferrerCode varchar(500) null,
    ReferringOrganisationCode varchar(500) null,
    OrganisationCodeTypeofReferrer varchar(500) null,
    DirectAccessReferralIndicator varchar(500) null,
    AmbulanceIncidentNumber varchar(500) null,
    OrganisationCodeConveyingAmbulanceTrust varchar(500) null,
    DurationofElectiveWait varchar(500) null,
    IntendedManagement varchar(500) null,
    DecidedToAdmitDateForThisProvider varchar(500) null,
    WaitingTimeMeasurementType varchar(500) null,
    LocationTypeCodeAtStartOfEpisode varchar(500) null,
    HRGCode varchar(500) null,
    HRGVersionNumber varchar(500) null,
    ProcedureSchemeInUse varchar(500) null,
    DominantGroupingVariableProcedure varchar(500) null,
    FCEHRG varchar(500) null,
    EpisodeHRGVersionNumber varchar(500) null,
    SpellCoreHRG varchar(500) null,
    SpellHRGVersionNumber varchar(500) null,
    NumberOfBabies varchar(500) null,
    FirstAntenatalAssessmentDate varchar(500) null,
    GMPCodeofGMPResponsibleforAntenatalCare varchar(500) null,
    CodeofGPPracticeRegisteredGMPAntenatalCare varchar(500) null,
    OrganisationCodeTypeGPPracticeRegisteredGMPAntenatalCare varchar(500) null,
    LocationClassOfDeliveryPlaceIntended varchar(500) null,
    LocationTypeofDeliveryPlaceIntended varchar(500) null,
    DeliveryPlaceChangeReason varchar(500) null,
    DeliveryPlaceTypeIntended varchar(500) null,
    AnaestheticGivenDuringLabourDelivery varchar(500) null,
    AnaestheticGivenPostDelivery varchar(500) null,
    GestationLengthLabourOnset varchar(500) null,
    LabourDeliveryOnsetMethod varchar(500) null,
    DeliveryDate varchar(500) null,
    GestationLengthAssessmentBaby varchar(500) null,
    LocalPatientIdentifierMother varchar(500) null,
    OrganisationCodeLocalPatientIdentifierMother varchar(500) null,
    OrganisationCodeTypeMother varchar(500) null,
    NHSNumberMother varchar(500) null,
    NHSNumberStatusIndicatorMother varchar(500) null,
    BirthDateMother varchar(500) null,
    AddressFormatCodeMother varchar(500) null,
    PatientUsualAddressMother varchar(500) null,
    PostcodeOfUsualAddressMother varchar(500) null,
    OrganisationCodePCTofResidenceMother varchar(500) null,
    OrganisationCodeTypePCTofResidenceMother varchar(500) null,
    UniqueBookingReferenceNumberConverted varchar(500) null,
    PatientPathwayIdentifier varchar(500) null,
    OrganisationCodePatientPathwayIdentifierIssuer varchar(500) null,
    ReferralToTreatmentPeriodStatus varchar(500) null,
    ReferralToTreatmentPeriodStartDate varchar(500) null,
    ReferralToTreatmentPeriodEndDate varchar(500) null,
    LeadCareActivityIndicator varchar(500) null,
    AgeatCDSActivityDate varchar(500) null,
    NHSServiceAgreementChangeDate varchar(500) null,
    CDSActivityDate varchar(500) null,
    AgeAsOnAdmission varchar(500) null,
    AdminCategoryAtStart varchar(500) null,
    HospitalProviderSpellDischargeReadyDate varchar(500) null,
    LocationType varchar(500) null,
    XMLVersion varchar(500) null,
    ConfidentialityCategoryDerived varchar(500) null,
    ReferralToTreatmentLengthDerived varchar(500) null,
    AgeRangePatientdDerivedFromDOB varchar(500) null,
    AgeRangeMotherDerivedFromDOB varchar(500) null,
    AreaCodeDerivedFromPostcode varchar(500) null,
    CDSGroup varchar(500) null,
    FinishedIndicator varchar(500) null,
    PCTDerivedfromGP varchar(500) null,
    PCTTypeDerivedfromGP varchar(500) null,
    GPPracticeDerived varchar(500) null,
    GPPracticeMotherDerived varchar(500) null,
    PCTDerivedfromderivedGPPractice varchar(500) null,
    PCTMotherDerivedfromderivedGPPractice varchar(500) null,
    SHAfromGPPractice varchar(500) null,
    SHATypefromGPPractice varchar(500) null,
    HospitalSpellDuration varchar(500) null,
    MonthOfBirth varchar(500) null,
    HomeBirthOrDelivery varchar(500) null,
    ElectoralWardFromPostcode varchar(500) null,
    PCTFromPostcode varchar(500) null,
    PCTTypefromPostcode varchar(500) null,
    SHAfromPostcode varchar(500) null,
    SHATypefromPostcode varchar(500) null,
    AreacodeFromProviderPostcode varchar(500) null,
    AgeAtEndOfEpisode varchar(500) null,
    AgeAtStartOfEpisode varchar(500) null,
    YearOfBirth varchar(500) null,
    YearOfBirthMother varchar(500) null,
    MonthOfBirthMother varchar(500) null,
    CensusArea varchar(500) null,
    Country varchar(500) null,
    CountyCode varchar(500) null,
    CensusED varchar(500) null,
    EDDistrictCode varchar(500) null,
    ElectoralWardCode varchar(500) null,
    GORCode varchar(500) null,
    LocalUnitaryAuthority varchar(500) null,
    OldSHACode varchar(500) null,
    ElectoralArea varchar(500) null,
    PrimeRecipient varchar(500) null,
    CopyRecipients varchar(500) null
);


create table omop_staging.sus_OverseasVisitor
(
    MessageId uniqueidentifier not null,
    constraint FK_omop_staging_sus_OverseasVisitor_MessageId foreign key (MessageId) references omop_staging.sus_APC (MessageId),
    OverseasVisitorStatusClassification varchar(500) null,
    OverseasVisitorStatusStartDate varchar(500) null
)

create clustered index IDX_omop_staging_sus_OverseasVisitor on omop_staging.sus_OverseasVisitor (MessageId);


create table omop_staging.sus_ICDDiagnosis
(
    MessageId uniqueidentifier not null,
    constraint FK_omop_staging_sus_ICDDiagnosis_MessageId foreign key (MessageId) references omop_staging.sus_APC (MessageId),
    DiagnosisICD varchar(500) null,
    PresentOnAdmissionIndicatorDiagnosis varchar(500) null,
    IsPrimaryDiagnosis bit not null
)

create clustered index IDX_omop_staging_sus_ICDDiagnosis on omop_staging.sus_ICDDiagnosis (MessageId);


create table omop_staging.sus_ReadDiagnosis
(
    MessageId uniqueidentifier not null,
    constraint FK_omop_staging_sus_ReadDiagnosis_MessageId foreign key (MessageId) references omop_staging.sus_APC (MessageId),
    DiagnosisRead varchar(500) not null,
    IsPrimaryDiagnosis bit not null
)

create clustered index IDX_omop_staging_sus_ReadDiagnosis on omop_staging.sus_ReadDiagnosis (MessageId);


create table omop_staging.sus_CareLocation
(
    MessageId uniqueidentifier not null,
    constraint FK_omop_staging_sus_CareLocation_MessageId foreign key (MessageId) references omop_staging.sus_APC (MessageId),
    WardCode varchar(500) null,
    WardSecurityLevel varchar(500) null,
    LocationClass varchar(500) null,
    SiteCodeOfTreatment varchar(500) null,
    OrganisationCodeTypeSiteCodeOfTreatment varchar(500) null,
    IntendedClinicalCareIntensity varchar(500) null,
    AgeGroupIntended varchar(500) null,
    SexOfPatients varchar(500) null,
    WardDayPeriodAvailability varchar(500) null,
    WardNightPeriodAvailability varchar(500) null,
    StartDate varchar(500) null,
    StartTimeWardStay varchar(500) null,
    EndDate varchar(500) null,
    EndTimeWardStay varchar(500) null
)

create clustered index IDX_omop_staging_sus_CareLocation on omop_staging.sus_CareLocation (MessageId);


create table omop_staging.sus_OPCSProcedure
(
    MessageId uniqueidentifier not null,
    constraint FK_omop_staging_sus_OPCSProcedure_MessageId foreign key (MessageId) references omop_staging.sus_APC (MessageId),
    ProcedureOPCS varchar(500) null,
    ProcedureDateOPCS varchar(500) null,
    MainOperatingHealthcareProfessionalCodeOpcs varchar(500) null,
    ProfessionalRegistrationIssuerCodeOpcs varchar(500) null,
    ResponsibleAnaesthetistCodeOpcs varchar(500) null,
    ResponsibleAnaesthetistRegBodyOpcs varchar(500) null,
    IsPrimaryProcedure bit not null
)

create clustered index IDX_omop_staging_sus_OPCSProcedure on omop_staging.sus_OPCSProcedure (MessageId);


create table omop_staging.sus_ReadProcedure
(
    MessageId uniqueidentifier not null,
    constraint FK_omop_staging_sus_ReadProcedure_MessageId foreign key (MessageId) references omop_staging.sus_APC (MessageId),
    ProcedureRead varchar(500) null,
    ProcedureDateRead varchar(500) null,
    IsPrimaryProcedure bit not null
)

create clustered index IDX_omop_staging_sus_ReadProcedure on omop_staging.sus_ReadProcedure (MessageId);


create table omop_staging.sus_Birth
(
    MessageId uniqueidentifier not null,
    constraint FK_omop_staging_sus_Birth_MessageId foreign key (MessageId) references omop_staging.sus_APC (MessageId),
    BirthOrderBaby varchar(500) null,
    DeliveryMethodBaby varchar(500) null,
    GestationLengthAssessmentBaby varchar(500) null,
    ResuscitationMethodBaby varchar(500) null,
    StatusOfPersonConductingDeliveryBaby varchar(500) null,
    LocalPatientIdentifierBaby varchar(500) null,
    OrganisationCodeLocalPatientIDBaby varchar(500) null,
    OrganisationCodeTypeLocalPatientIDBaby varchar(500) null,
    NHSNumberBaby varchar(500) null,
    NHSNumberStatusIndicatorBaby varchar(500) null,
    BirthDateBabyBaby varchar(500) null,
    BirthWeightBaby varchar(500) null,
    LiveOrStillBirthBaby varchar(500) null,
    SexBaby varchar(500) null,
    BirthLocationType varchar(500) null,
    LocationClassDeliveryPlaceActual varchar(500) null,
    DeliveryPlaceTypeActual varchar(500) null
)

create clustered index IDX_omop_staging_sus_Birth on omop_staging.sus_Birth (MessageId);


create table omop_staging.sus_CriticalCare
(
    MessageId uniqueidentifier not null,
    constraint FK_omop_staging_sus_CriticalCare_MessageId foreign key (MessageId) references omop_staging.sus_APC (MessageId),
    CriticalCareLocalIdentifier varchar(500) null,
    CriticalCareStartDate varchar(500) null,
    CriticalCareUnitFunction varchar(500) null,
    AdvancedRespiratorySupportDays varchar(500) null,
    BasicRespiratorySupportDays varchar(500) null,
    AdvancedCardiovascularSupportDays varchar(500) null,
    BasicCardiovascularSupportDays varchar(500) null,
    RenalSupportDays varchar(500) null,
    NeurologicalSupportDays varchar(500) null,
    DermatologicalSupportDays varchar(500) null,
    LiverSupportDays varchar(500) null,
    CriticalCareLevel2Days varchar(500) null,
    CriticalCareLevel3Days varchar(500) null,
    CriticalCareDischargeDate varchar(500) null,
    CriticalCareUnitBedConfiguration varchar(500) null,
    CriticalCareAdmissionSource varchar(500) null,
    CriticalCareSourceLocation varchar(500) null,
    CriticalCareAdmissionType varchar(500) null,
    GastroIntestinalSupportDays varchar(500) null,
    OrganSupportMaximum varchar(500) null,
    CriticalCareDischargeReadyDate varchar(500) null,
    CriticalCareDischargeReadyTime varchar(500) null,
    CriticalCareDischargeStatus varchar(500) null,
    CriticalCareDischargeDestination varchar(500) null,
    CriticalCareDischargeLocation varchar(500) null,
    CriticalCareDischargeTime varchar(500) null,
    CriticalCareActivityToEpisodeRelationshipDerived varchar(500) null,
    CriticalCarePeriodSequenceNumber varchar(500) null,
    CriticalCareStartTime varchar(500) null,
    CriticalCarePeriodType varchar(500) null
)

create clustered index IDX_omop_staging_sus_CriticalCare on omop_staging.sus_CriticalCare (MessageId);


create type omop_staging.sus_APC_row as table
(
    MessageId uniqueidentifier not null,
    GeneratedRecordIdentifier varchar(500) null,
    PBRSpellID varchar(500) null,
    ReasonForAccess varchar(500) null,
    CDSType varchar(500) null,
    ProtocolIdentifier varchar(500) null,
    UniqueCDSIdentifier varchar(500) null,
    UpdateType varchar(500) null,
    BulkReplacementCDSGroup varchar(500) null,
    TestIndicator varchar(500) null,
    ApplicableDatetime varchar(500) null,
    CensusDate varchar(500) null,
    ExtractDatetime varchar(500) null,
    ReportPeriodStartDate varchar(500) null,
    ReportPeriodEndDate varchar(500) null,
    OrganisationCodeSenderOfTransaction varchar(500) null,
    OrganisationCodeTypeofSender varchar(500) null,
    SubmissionDate varchar(500) null,
    CDSInterchangeID varchar(500) null,
    LocalPatientIdentifier varchar(500) null,
    OrganisationCodeLocalPatientIdentifier varchar(500) null,
    OrganisationCodeTypeLocalPatientIdentifier varchar(500) null,
    NHSNumber varchar(500) null,
    DateofBirth varchar(500) null,
    BirthWeight varchar(500) null,
    LiveOrStillBirth varchar(500) null,
    CarerSupportIndicator varchar(500) null,
    LegalStatusClassificationOnAdmissionPsychiatricCensusOnly varchar(500) null,
    EthnicGroup varchar(500) null,
    MaritalStatusPsychiatricCensusOnly varchar(500) null,
    NHSNumberTraceStatus varchar(500) null,
    WithheldIdentityReason varchar(500) null,
    Sex varchar(500) null,
    PregnancyTotalPreviousPregnancies varchar(500) null,
    NameFormatCode varchar(500) null,
    PatientName varchar(500) null,
    PersonTitle varchar(500) null,
    PersonGivenName varchar(500) null,
    PersonFamilyName varchar(500) null,
    PersonNameSuffix varchar(500) null,
    PersonInitials varchar(500) null,
    AddressFormatCode varchar(500) null,
    PatientUsualAddress varchar(500) null,
    Postcode varchar(500) null,
    OrganisationCodeResidenceResponsibility varchar(500) null,
    PCTofResidence varchar(500) null,
    OrganisationCodeTypePCTofResidence varchar(500) null,
    OSVClassificationatCDSActivityDate varchar(500) null,
    HospitalProviderSpellNumber varchar(500) null,
    AdministrativeCategory varchar(500) null,
    PatientClassification varchar(500) null,
    AdmissionMethodHospitalProviderSpell varchar(500) null,
    DischargeDestinationHospitalProviderSpell varchar(500) null,
    DischargeMethodHospitalProviderSpell varchar(500) null,
    SourceOfAdmissionHospitalProviderSpell varchar(500) null,
    StartDateHospitalProviderSpell varchar(500) null,
    StartTimeHospitalProviderSpell varchar(500) null,
    DischargeDateFromHospitalProviderSpell varchar(500) null,
    DischargeTimeHospitalProviderSpell varchar(500) null,
    DischargeToHospitalAtHomeServiceIndicator varchar(500) null,
    EpisodeNumber varchar(500) null,
    FirstRegularDayNightAdmission varchar(500) null,
    LastEpisodeInSpellIndicator varchar(500) null,
    NeonatalLevelOfCare varchar(500) null,
    OperationStatus varchar(500) null,
    PsychiatricPatientStatus varchar(500) null,
    StartDateConsultantEpisode varchar(500) null,
    StartTimeEpisode varchar(500) null,
    EndDateConsultantEpisode varchar(500) null,
    EndTimeEpisode varchar(500) null,
    LengthOfStayAdjustmentRehabilitation varchar(500) null,
    LengthOfStayAdjustmentSpecialistPalliativeCare varchar(500) null,
    CommissioningSerialNumber varchar(500) null,
    NHSServiceAgreementLineNumber varchar(500) null,
    ProviderReferenceNumber varchar(500) null,
    CommissionerReferenceNumber varchar(500) null,
    OrganisationCodeCodeOfProvider varchar(500) null,
    OrganisationCodeTypeOfProvider varchar(500) null,
    OrganisationCodeCodeOfCommissioner varchar(500) null,
    OrganisationCodeTypeofCommissioner varchar(500) null,
    ConsultantCode varchar(500) null,
    MainSpecialtyCode varchar(500) null,
    TreatmentFunctionCode varchar(500) null,
    LocalSubSpecialtyCode varchar(500) null,
    MultiProfessionalOrMultidisciplinaryIndCode varchar(500) null,
    RehabilitationAssessmentTeamType varchar(500) null,
    DiagnosisSchemeInUseICD varchar(500) null,
    DiagnosisSchemeInUseRead varchar(500) null,
    ProcedureSchemeInUseOPCS varchar(500) null,
    ProcedureSchemeInUseREAD varchar(500) null,
    WardCodeAtEpisodeStartDate varchar(500) null,
    WardSecurityLevelAtEpisodeStartDate varchar(500) null,
    LocationClassAtEpisodeStartDate varchar(500) null,
    SiteCodeOfTreatmentAtEpisodeStartDate varchar(500) null,
    OrganisationCodeTypeSiteCodeOfTreatmentAtStartOfEpisode varchar(500) null,
    IntendedClinicalCareIntensityAtStartOfEpisode varchar(500) null,
    AgeGroupIntendedAtStartOfEpisode varchar(500) null,
    SexOfPatientsAtStartOfEpisode varchar(500) null,
    WardDayPeriodAvailability varchar(500) null,
    WardNightPeriodAvailability varchar(500) null,
    WardCodeAtEpisodeEndDate varchar(500) null,
    WardSecurityLevelAtEpisodeEndDate varchar(500) null,
    LocationClassAtEpisodeEndDate varchar(500) null,
    SiteCodeOfTreatmentAtEpisodeEndDate varchar(500) null,
    OrganisationCodeTypeSiteCodeOfTreatmentAtEpisodeEndDate varchar(500) null,
    IntendedClinicalCareIntensityAtEpisodeEndDate varchar(500) null,
    AgeGroupIntendedAtEpisodeEndDate varchar(500) null,
    SexOfPatientsAtEpisodeEndDate varchar(500) null,
    WardDayPeriodAvailabilityAtEpisodeEndDate varchar(500) null,
    WardNightPeriodAvailabilityAtEpisodeEndDate varchar(500) null,
    GeneralMedicalPractitionerCodeofRegisteredGMP varchar(500) null,
    PracticeCodeofRegisteredGP varchar(500) null,
    OrganisationCodeTypeofRegisteredGP varchar(500) null,
    ReferrerCode varchar(500) null,
    ReferringOrganisationCode varchar(500) null,
    OrganisationCodeTypeofReferrer varchar(500) null,
    DirectAccessReferralIndicator varchar(500) null,
    AmbulanceIncidentNumber varchar(500) null,
    OrganisationCodeConveyingAmbulanceTrust varchar(500) null,
    DurationofElectiveWait varchar(500) null,
    IntendedManagement varchar(500) null,
    DecidedToAdmitDateForThisProvider varchar(500) null,
    WaitingTimeMeasurementType varchar(500) null,
    LocationTypeCodeAtStartOfEpisode varchar(500) null,
    HRGCode varchar(500) null,
    HRGVersionNumber varchar(500) null,
    ProcedureSchemeInUse varchar(500) null,
    DominantGroupingVariableProcedure varchar(500) null,
    FCEHRG varchar(500) null,
    EpisodeHRGVersionNumber varchar(500) null,
    SpellCoreHRG varchar(500) null,
    SpellHRGVersionNumber varchar(500) null,
    NumberOfBabies varchar(500) null,
    FirstAntenatalAssessmentDate varchar(500) null,
    GMPCodeofGMPResponsibleforAntenatalCare varchar(500) null,
    CodeofGPPracticeRegisteredGMPAntenatalCare varchar(500) null,
    OrganisationCodeTypeGPPracticeRegisteredGMPAntenatalCare varchar(500) null,
    LocationClassOfDeliveryPlaceIntended varchar(500) null,
    LocationTypeofDeliveryPlaceIntended varchar(500) null,
    DeliveryPlaceChangeReason varchar(500) null,
    DeliveryPlaceTypeIntended varchar(500) null,
    AnaestheticGivenDuringLabourDelivery varchar(500) null,
    AnaestheticGivenPostDelivery varchar(500) null,
    GestationLengthLabourOnset varchar(500) null,
    LabourDeliveryOnsetMethod varchar(500) null,
    DeliveryDate varchar(500) null,
    GestationLengthAssessmentBaby varchar(500) null,
    LocalPatientIdentifierMother varchar(500) null,
    OrganisationCodeLocalPatientIdentifierMother varchar(500) null,
    OrganisationCodeTypeMother varchar(500) null,
    NHSNumberMother varchar(500) null,
    NHSNumberStatusIndicatorMother varchar(500) null,
    BirthDateMother varchar(500) null,
    AddressFormatCodeMother varchar(500) null,
    PatientUsualAddressMother varchar(500) null,
    PostcodeOfUsualAddressMother varchar(500) null,
    OrganisationCodePCTofResidenceMother varchar(500) null,
    OrganisationCodeTypePCTofResidenceMother varchar(500) null,
    UniqueBookingReferenceNumberConverted varchar(500) null,
    PatientPathwayIdentifier varchar(500) null,
    OrganisationCodePatientPathwayIdentifierIssuer varchar(500) null,
    ReferralToTreatmentPeriodStatus varchar(500) null,
    ReferralToTreatmentPeriodStartDate varchar(500) null,
    ReferralToTreatmentPeriodEndDate varchar(500) null,
    LeadCareActivityIndicator varchar(500) null,
    AgeatCDSActivityDate varchar(500) null,
    NHSServiceAgreementChangeDate varchar(500) null,
    CDSActivityDate varchar(500) null,
    AgeAsOnAdmission varchar(500) null,
    AdminCategoryAtStart varchar(500) null,
    HospitalProviderSpellDischargeReadyDate varchar(500) null,
    LocationType varchar(500) null,
    XMLVersion varchar(500) null,
    ConfidentialityCategoryDerived varchar(500) null,
    ReferralToTreatmentLengthDerived varchar(500) null,
    AgeRangePatientdDerivedFromDOB varchar(500) null,
    AgeRangeMotherDerivedFromDOB varchar(500) null,
    AreaCodeDerivedFromPostcode varchar(500) null,
    CDSGroup varchar(500) null,
    FinishedIndicator varchar(500) null,
    PCTDerivedfromGP varchar(500) null,
    PCTTypeDerivedfromGP varchar(500) null,
    GPPracticeDerived varchar(500) null,
    GPPracticeMotherDerived varchar(500) null,
    PCTDerivedfromderivedGPPractice varchar(500) null,
    PCTMotherDerivedfromderivedGPPractice varchar(500) null,
    SHAfromGPPractice varchar(500) null,
    SHATypefromGPPractice varchar(500) null,
    HospitalSpellDuration varchar(500) null,
    MonthOfBirth varchar(500) null,
    HomeBirthOrDelivery varchar(500) null,
    ElectoralWardFromPostcode varchar(500) null,
    PCTFromPostcode varchar(500) null,
    PCTTypefromPostcode varchar(500) null,
    SHAfromPostcode varchar(500) null,
    SHATypefromPostcode varchar(500) null,
    AreacodeFromProviderPostcode varchar(500) null,
    AgeAtEndOfEpisode varchar(500) null,
    AgeAtStartOfEpisode varchar(500) null,
    YearOfBirth varchar(500) null,
    YearOfBirthMother varchar(500) null,
    MonthOfBirthMother varchar(500) null,
    CensusArea varchar(500) null,
    Country varchar(500) null,
    CountyCode varchar(500) null,
    CensusED varchar(500) null,
    EDDistrictCode varchar(500) null,
    ElectoralWardCode varchar(500) null,
    GORCode varchar(500) null,
    LocalUnitaryAuthority varchar(500) null,
    OldSHACode varchar(500) null,
    ElectoralArea varchar(500) null,
    PrimeRecipient varchar(500) null,
    CopyRecipients varchar(500) null
);

create type omop_staging.sus_OverseasVisitor_row as table
(
    MessageId uniqueidentifier not null,
    OverseasVisitorStatusClassification varchar(500) null,
    OverseasVisitorStatusStartDate varchar(500) null
)

create type omop_staging.sus_ICDDiagnosis_row as table
(
    MessageId uniqueidentifier not null,
    DiagnosisICD varchar(500) null,
    PresentOnAdmissionIndicatorDiagnosis varchar(500) null,
    IsPrimaryDiagnosis bit not null
)

create type omop_staging.sus_ReadDiagnosis_row as table
(
    MessageId uniqueidentifier not null,
    DiagnosisRead varchar(500) not null,
    IsPrimaryDiagnosis bit not null
)

create type omop_staging.sus_CareLocation_row as table
(
    MessageId uniqueidentifier not null,
    WardCode varchar(500) null,
    WardSecurityLevel varchar(500) null,
    LocationClass varchar(500) null,
    SiteCodeOfTreatment varchar(500) null,
    OrganisationCodeTypeSiteCodeOfTreatment varchar(500) null,
    IntendedClinicalCareIntensity varchar(500) null,
    AgeGroupIntended varchar(500) null,
    SexOfPatients varchar(500) null,
    WardDayPeriodAvailability varchar(500) null,
    WardNightPeriodAvailability varchar(500) null,
    StartDate varchar(500) null,
    StartTimeWardStay varchar(500) null,
    EndDate varchar(500) null,
    EndTimeWardStay varchar(500) null
)

create type omop_staging.sus_OPCSProcedure_row as table
(
    MessageId uniqueidentifier not null,
    ProcedureOPCS varchar(500) null,
    ProcedureDateOPCS varchar(500) null,
    MainOperatingHealthcareProfessionalCodeOpcs varchar(500) null,
    ProfessionalRegistrationIssuerCodeOpcs varchar(500) null,
    ResponsibleAnaesthetistCodeOpcs varchar(500) null,
    ResponsibleAnaesthetistRegBodyOpcs varchar(500) null,
    IsPrimaryProcedure bit not null
)

create type omop_staging.sus_ReadProcedure_row as table
(
    MessageId uniqueidentifier not null,
    ProcedureRead varchar(500) null,
    ProcedureDateRead varchar(500) null,
    IsPrimaryProcedure bit not null
)

create type omop_staging.sus_Birth_row as table
(
    MessageId uniqueidentifier not null,
    BirthOrderBaby varchar(500) null,
    DeliveryMethodBaby varchar(500) null,
    GestationLengthAssessmentBaby varchar(500) null,
    ResuscitationMethodBaby varchar(500) null,
    StatusOfPersonConductingDeliveryBaby varchar(500) null,
    LocalPatientIdentifierBaby varchar(500) null,
    OrganisationCodeLocalPatientIDBaby varchar(500) null,
    OrganisationCodeTypeLocalPatientIDBaby varchar(500) null,
    NHSNumberBaby varchar(500) null,
    NHSNumberStatusIndicatorBaby varchar(500) null,
    BirthDateBabyBaby varchar(500) null,
    BirthWeightBaby varchar(500) null,
    LiveOrStillBirthBaby varchar(500) null,
    SexBaby varchar(500) null,
    BirthLocationType varchar(500) null,
    LocationClassDeliveryPlaceActual varchar(500) null,
    DeliveryPlaceTypeActual varchar(500) null
)

create type omop_staging.sus_CriticalCare_row as table
(
    MessageId uniqueidentifier not null,
    CriticalCareLocalIdentifier varchar(500) null,
    CriticalCareStartDate varchar(500) null,
    CriticalCareUnitFunction varchar(500) null,
    AdvancedRespiratorySupportDays varchar(500) null,
    BasicRespiratorySupportDays varchar(500) null,
    AdvancedCardiovascularSupportDays varchar(500) null,
    BasicCardiovascularSupportDays varchar(500) null,
    RenalSupportDays varchar(500) null,
    NeurologicalSupportDays varchar(500) null,
    DermatologicalSupportDays varchar(500) null,
    LiverSupportDays varchar(500) null,
    CriticalCareLevel2Days varchar(500) null,
    CriticalCareLevel3Days varchar(500) null,
    CriticalCareDischargeDate varchar(500) null,
    CriticalCareUnitBedConfiguration varchar(500) null,
    CriticalCareAdmissionSource varchar(500) null,
    CriticalCareSourceLocation varchar(500) null,
    CriticalCareAdmissionType varchar(500) null,
    GastroIntestinalSupportDays varchar(500) null,
    OrganSupportMaximum varchar(500) null,
    CriticalCareDischargeReadyDate varchar(500) null,
    CriticalCareDischargeReadyTime varchar(500) null,
    CriticalCareDischargeStatus varchar(500) null,
    CriticalCareDischargeDestination varchar(500) null,
    CriticalCareDischargeLocation varchar(500) null,
    CriticalCareDischargeTime varchar(500) null,
    CriticalCareActivityToEpisodeRelationshipDerived varchar(500) null,
    CriticalCarePeriodSequenceNumber varchar(500) null,
    CriticalCareStartTime varchar(500) null,
    CriticalCarePeriodType varchar(500) null
)