create table omop_staging.sus_AE
(
    MessageId uniqueidentifier not null,
    constraint PK_omop_staging_sus_AE_MessageId primary key (MessageId),
    GeneratedRecordIdentifier varchar(max) null,
    ReasonForAccess varchar(max) null,
    CDStype varchar(max) null,
    ProtocolIdentifier varchar(max) null,
    UniqueCDSidentifier varchar(max) null,
    UpdateType varchar(max) null,
    BulkreplacementCDSgroup varchar(max) null,
    TestIndicator varchar(max) null,
    ApplicableDatetime varchar(max) null,
    CensusDate varchar(max) null,
    ExtractDatetime varchar(max) null,
    ReportPeriodStartDate varchar(max) null,
    ReportPeriodEndDate varchar(max) null,
    OrganisationCodeSenderOfTransaction varchar(max) null,
    OrganisationCodeTypeofSender varchar(max) null,
    CDSInterchangeID varchar(max) null,
    LocalPatientIdentifier varchar(max) null,
    OrganisationCodeLocalPatientIdentifier varchar(max) null,
    OrganisationCodeTypeLocalPatientIdentifier varchar(max) null,
    NHSNumber varchar(max) null,
    DateOfBirth varchar(max) null,
    CarerSupportIndicator varchar(max) null,
    NHSNumberTraceStatus varchar(max) null,
    WithheldIdentityReason varchar(max) null,
    Sex varchar(max) null,
    NameFormatCode varchar(max) null,
    PatientName varchar(max) null,
    PersonTitle varchar(max) null,
    PersonGivenName varchar(max) null,
    PersonFamilyName varchar(max) null,
    PersonNameSuffix varchar(max) null,
    PersonInitials varchar(max) null,
    AddressFormatCode varchar(max) null,
    PatientUsualAddress varchar(max) null,
    Postcode varchar(max) null,
    OrganisationCodeResidenceResponsibility varchar(max) null,
    PCTofResidence varchar(max) null,
    OrganisationCodeTypePCTofResidence varchar(max) null,
    EthnicCategory varchar(max) null,
    OSVClassificationatCDSActivityDate varchar(max) null,
    GeneralMedicalPractitionerCodeofRegisteredGMP varchar(max) null,
    PracticeCodeofRegisteredGP varchar(max) null,
    OrganisationCodeTypeofRegisteredGP varchar(max) null,
    AEAttendanceNumber varchar(max) null,
    AEArrivalMode varchar(max) null,
    AEAttendanceCategory varchar(max) null,
    AEAttendanceDisposal varchar(max) null,
    AEIncidentLocationType varchar(max) null,
    AEPatientGroup varchar(max) null,
    SourceofReferralForAE varchar(max) null,
    ArrivalDate varchar(max) null,
    ArrivalTime varchar(max) null,
    AEAttendanceConclusionTime varchar(max) null,
    AEAttendanceConclusionDate varchar(max) null,
    AEDepartureTime varchar(max) null,
    AEDepartureDate varchar(max) null,
    AEInitialAssessmentTimefirstandunplannedfollowupattendancesonly varchar(max) null,
    AEInitialAssessmentDate varchar(max) null,
    AETimeSeenForTreatment varchar(max) null,
    SiteCodeOfTreatment varchar(max) null,
    WaitingTimeMeasurementType varchar(max) null,
    AmbulanceIncidentNumber varchar(max) null,
    OrganisationCodeConveyingAmbulanceTrust varchar(max) null,
    CommissioningSerialNumber varchar(max) null,
    NHSServiceAgreementLineNumber varchar(max) null,
    ProviderReferenceNumber varchar(max) null,
    CommissionerReferenceNumber varchar(max) null,
    OrganisationCodeCodeOfProvider varchar(max) null,
    OrganisationCodeTypeOfProvider varchar(max) null,
    OrganisationCodeCodeOfCommissioner varchar(max) null,
    OrganisationCodeTypeOfCommissioner varchar(max) null,
    AEStaffMemberCode varchar(max) null,
    DiagnosisSchemeInUse varchar(max) null,
    InvestigationSchemeInUse varchar(max) null,
    TreatmentSchemeInUse varchar(max) null,
    HRGCode varchar(max) null,
    HRGVersionNumber varchar(max) null,
    ProcedureSchemeInUse varchar(max) null,
    DominantGroupingVariableProcedure varchar(max) null,
    FCEHRG varchar(max) null,
    SpellCOREHRGVersionNo varchar(max) null,
    PBRGeneratedCoreHRGforInformation varchar(max) null,
    PBRGeneratedCoreHRGVersionforInformation varchar(max) null,
    UniqueBookingReferenceNumberConverted varchar(max) null,
    PatientPathwayIdentifier varchar(max) null,
    OrganisationCodePatientPathwayIdentifierIssuer varchar(max) null,
    ReferralToTreatmentPeriodStatus varchar(max) null,
    ReferralToTreatmentPeriodStartDate varchar(max) null,
    ReferralToTreatmentPeriodEndDate varchar(max) null,
    LeadCareActivityIndicator varchar(max) null,
    AgeatCDSActivityDate varchar(max) null,
    NHSServiceAgreementChangeDate varchar(max) null,
    CDSActivityDate varchar(max) null,
    AEDepartmentType varchar(max) null,
    XMLVersion varchar(max) null,
    ConfidentialityCategoryDerived varchar(max) null,
    ReferralToTreatmentLengthDerived varchar(max) null,
    AEAssessmentWaitTime varchar(max) null,
    AEConclusionWaitTime varchar(max) null,
    AEDuration varchar(max) null,
    AETreatmentWait varchar(max) null,
    AgerangepatientderivedfromDOB varchar(max) null,
    AreaCodeDerivedFromPostcode varchar(max) null,
    CDSGroup varchar(max) null,
    FinishedIndicator varchar(max) null,
    PCTDerivedfromGP varchar(max) null,
    PCTTypeDerivedfromGP varchar(max) null,
    GPPracticeDerived varchar(max) null,
    PCTDerivedfromderivedGPPractice varchar(max) null,
    SHAfromGPPractice varchar(max) null,
    SHATypefromGPPractice varchar(max) null,
    MonthOfBirth varchar(max) null,
    ElectoralWardFromPostcode varchar(max) null,
    PCTfrompostcode varchar(max) null,
    PCTTypefromPostcode varchar(max) null,
    SHAfromPostcode varchar(max) null,
    SHATypefromPostcode varchar(max) null,
    AreaCodeFromProviderPostcode varchar(max) null,
    AgeAtEndOfEpisode varchar(max) null,
    AgeAtStartOfEpisode varchar(max) null,
    YearOfBirth varchar(max) null,
    CensusArea varchar(max) null,
    Country varchar(max) null,
    CountyCode varchar(max) null,
    CensusED varchar(max) null,
    EDDistrictCode varchar(max) null,
    ElectoralWardCode varchar(max) null,
    GORCode varchar(max) null,
    LocalUnitaryAuthority varchar(max) null,
    OldSHACode varchar(max) null,
    ElectoralArea varchar(max) null,
    PrimeRecipient varchar(max) null,
    CopyRecipients varchar(max) null
);

create type omop_staging.sus_AE_row as table
(
    MessageId uniqueidentifier not null,
    GeneratedRecordIdentifier varchar(max) null,
    ReasonForAccess varchar(max) null,
    CDStype varchar(max) null,
    ProtocolIdentifier varchar(max) null,
    UniqueCDSidentifier varchar(max) null,
    UpdateType varchar(max) null,
    BulkreplacementCDSgroup varchar(max) null,
    TestIndicator varchar(max) null,
    ApplicableDatetime varchar(max) null,
    CensusDate varchar(max) null,
    ExtractDatetime varchar(max) null,
    ReportPeriodStartDate varchar(max) null,
    ReportPeriodEndDate varchar(max) null,
    OrganisationCodeSenderOfTransaction varchar(max) null,
    OrganisationCodeTypeofSender varchar(max) null,
    CDSInterchangeID varchar(max) null,
    LocalPatientIdentifier varchar(max) null,
    OrganisationCodeLocalPatientIdentifier varchar(max) null,
    OrganisationCodeTypeLocalPatientIdentifier varchar(max) null,
    NHSNumber varchar(max) null,
    DateOfBirth varchar(max) null,
    CarerSupportIndicator varchar(max) null,
    NHSNumberTraceStatus varchar(max) null,
    WithheldIdentityReason varchar(max) null,
    Sex varchar(max) null,
    NameFormatCode varchar(max) null,
    PatientName varchar(max) null,
    PersonTitle varchar(max) null,
    PersonGivenName varchar(max) null,
    PersonFamilyName varchar(max) null,
    PersonNameSuffix varchar(max) null,
    PersonInitials varchar(max) null,
    AddressFormatCode varchar(max) null,
    PatientUsualAddress varchar(max) null,
    Postcode varchar(max) null,
    OrganisationCodeResidenceResponsibility varchar(max) null,
    PCTofResidence varchar(max) null,
    OrganisationCodeTypePCTofResidence varchar(max) null,
    EthnicCategory varchar(max) null,
    OSVClassificationatCDSActivityDate varchar(max) null,
    GeneralMedicalPractitionerCodeofRegisteredGMP varchar(max) null,
    PracticeCodeofRegisteredGP varchar(max) null,
    OrganisationCodeTypeofRegisteredGP varchar(max) null,
    AEAttendanceNumber varchar(max) null,
    AEArrivalMode varchar(max) null,
    AEAttendanceCategory varchar(max) null,
    AEAttendanceDisposal varchar(max) null,
    AEIncidentLocationType varchar(max) null,
    AEPatientGroup varchar(max) null,
    SourceofReferralForAE varchar(max) null,
    ArrivalDate varchar(max) null,
    ArrivalTime varchar(max) null,
    AEAttendanceConclusionTime varchar(max) null,
    AEAttendanceConclusionDate varchar(max) null,
    AEDepartureTime varchar(max) null,
    AEDepartureDate varchar(max) null,
    AEInitialAssessmentTimefirstandunplannedfollowupattendancesonly varchar(max) null,
    AEInitialAssessmentDate varchar(max) null,
    AETimeSeenForTreatment varchar(max) null,
    SiteCodeOfTreatment varchar(max) null,
    WaitingTimeMeasurementType varchar(max) null,
    AmbulanceIncidentNumber varchar(max) null,
    OrganisationCodeConveyingAmbulanceTrust varchar(max) null,
    CommissioningSerialNumber varchar(max) null,
    NHSServiceAgreementLineNumber varchar(max) null,
    ProviderReferenceNumber varchar(max) null,
    CommissionerReferenceNumber varchar(max) null,
    OrganisationCodeCodeOfProvider varchar(max) null,
    OrganisationCodeTypeOfProvider varchar(max) null,
    OrganisationCodeCodeOfCommissioner varchar(max) null,
    OrganisationCodeTypeOfCommissioner varchar(max) null,
    AEStaffMemberCode varchar(max) null,
    DiagnosisSchemeInUse varchar(max) null,
    InvestigationSchemeInUse varchar(max) null,
    TreatmentSchemeInUse varchar(max) null,
    HRGCode varchar(max) null,
    HRGVersionNumber varchar(max) null,
    ProcedureSchemeInUse varchar(max) null,
    DominantGroupingVariableProcedure varchar(max) null,
    FCEHRG varchar(max) null,
    SpellCOREHRGVersionNo varchar(max) null,
    PBRGeneratedCoreHRGforInformation varchar(max) null,
    PBRGeneratedCoreHRGVersionforInformation varchar(max) null,
    UniqueBookingReferenceNumberConverted varchar(max) null,
    PatientPathwayIdentifier varchar(max) null,
    OrganisationCodePatientPathwayIdentifierIssuer varchar(max) null,
    ReferralToTreatmentPeriodStatus varchar(max) null,
    ReferralToTreatmentPeriodStartDate varchar(max) null,
    ReferralToTreatmentPeriodEndDate varchar(max) null,
    LeadCareActivityIndicator varchar(max) null,
    AgeatCDSActivityDate varchar(max) null,
    NHSServiceAgreementChangeDate varchar(max) null,
    CDSActivityDate varchar(max) null,
    AEDepartmentType varchar(max) null,
    XMLVersion varchar(max) null,
    ConfidentialityCategoryDerived varchar(max) null,
    ReferralToTreatmentLengthDerived varchar(max) null,
    AEAssessmentWaitTime varchar(max) null,
    AEConclusionWaitTime varchar(max) null,
    AEDuration varchar(max) null,
    AETreatmentWait varchar(max) null,
    AgerangepatientderivedfromDOB varchar(max) null,
    AreaCodeDerivedFromPostcode varchar(max) null,
    CDSGroup varchar(max) null,
    FinishedIndicator varchar(max) null,
    PCTDerivedfromGP varchar(max) null,
    PCTTypeDerivedfromGP varchar(max) null,
    GPPracticeDerived varchar(max) null,
    PCTDerivedfromderivedGPPractice varchar(max) null,
    SHAfromGPPractice varchar(max) null,
    SHATypefromGPPractice varchar(max) null,
    MonthOfBirth varchar(max) null,
    ElectoralWardFromPostcode varchar(max) null,
    PCTfrompostcode varchar(max) null,
    PCTTypefromPostcode varchar(max) null,
    SHAfromPostcode varchar(max) null,
    SHATypefromPostcode varchar(max) null,
    AreaCodeFromProviderPostcode varchar(max) null,
    AgeAtEndOfEpisode varchar(max) null,
    AgeAtStartOfEpisode varchar(max) null,
    YearOfBirth varchar(max) null,
    CensusArea varchar(max) null,
    Country varchar(max) null,
    CountyCode varchar(max) null,
    CensusED varchar(max) null,
    EDDistrictCode varchar(max) null,
    ElectoralWardCode varchar(max) null,
    GORCode varchar(max) null,
    LocalUnitaryAuthority varchar(max) null,
    OldSHACode varchar(max) null,
    ElectoralArea varchar(max) null,
    PrimeRecipient varchar(max) null,
    CopyRecipients varchar(max) null
);


create table omop_staging.sus_AE_diagnosis
(
    MessageId uniqueidentifier not null,
    AccidentAndEmergencyDiagnosis varchar(max) not null,
    constraint FK_omop_staging_sus_AE_diagnosis_MessageId foreign key (MessageId) references omop_staging.sus_AE (MessageId)
);

create type omop_staging.sus_AE_diagnosis_row as table
(
    MessageId uniqueidentifier not null,
    AccidentAndEmergencyDiagnosis varchar(max) not null
);

create table omop_staging.sus_AE_investigation
(
    MessageId uniqueidentifier not null,
    AccidentAndEmergencyInvestigation varchar(max) not null,
    constraint FK_omop_staging_sus_AE_investigation foreign key (MessageId) references omop_staging.sus_AE (MessageId)
);

create type omop_staging.sus_AE_investigation_row as table
(
    MessageId uniqueidentifier not null,
    AccidentAndEmergencyInvestigation varchar(max) not null
);


create table omop_staging.sus_AE_treatment
(
    MessageId uniqueidentifier not null,
    AccidentAndEmergencyTreatment varchar(max) not null,
    constraint FK_omop_staging_sus_AE_treatment foreign key (MessageId) references omop_staging.sus_AE (MessageId)
);

create type omop_staging.sus_AE_treatment_row as table
(
    MessageId uniqueidentifier not null,
    AccidentAndEmergencyTreatment varchar(max) not null
);